function interactive
%INTERACTIVE Bounded controls for the P08 Interface Control Contract.
modelFcn = @model; % Keep P08 bound after the launcher removes its path.
fig = uifigure('Name','P08 Write an Interface Control Contract', ...
    'Position',[20 40 1660 860]);
layout = uigridlayout(fig,[4 9]);
layout.RowHeight = {'1x','1x',30,80};
layout.ColumnWidth = {'1x','1x','1x','1x','1x','1x','1x','1x','1x'};

clauseAxes = uiaxes(layout);
clauseAxes.Layout.Row = 1; clauseAxes.Layout.Column = [1 5];
valueAxes = uiaxes(layout);
valueAxes.Layout.Row = 2; valueAxes.Layout.Column = [1 5];
summary = uilabel(layout,'WordWrap','on','FontName','Courier New');
summary.Layout.Row = [1 2]; summary.Layout.Column = [6 9];

label = uilabel(layout,'Text','Source angle (deg)', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 1;
sourceAngle = uispinner(layout,'Limits',[-360 360], ...
    'Step',5,'Value',30.021978021978);
sourceAngle.Layout.Row = 4; sourceAngle.Layout.Column = 1;

label = uilabel(layout,'Text','Payload length (word)', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 2;
payloadWords = uispinner(layout,'Limits',[0 16],'Step',1,'Value',6);
payloadWords.RoundFractionalValues = 'on';
payloadWords.Layout.Row = 4; payloadWords.Layout.Column = 2;

label = uilabel(layout,'Text','Sender version (-)', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 3;
senderVersion = uispinner(layout,'Limits',[0 255],'Step',1,'Value',1);
senderVersion.RoundFractionalValues = 'on';
senderVersion.Layout.Row = 4; senderVersion.Layout.Column = 3;

label = uilabel(layout,'Text','Sequence (count)', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 4;
sequenceNumber = uispinner(layout,'Limits',[0 65535], ...
    'Step',1,'Value',42);
sequenceNumber.RoundFractionalValues = 'on';
sequenceNumber.Layout.Row = 4; sequenceNumber.Layout.Column = 4;

label = uilabel(layout,'Text','P07 source quality', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 5;
sourceQuality = uicheckbox(layout,'Text','Valid','Value',true);
sourceQuality.Layout.Row = 4; sourceQuality.Layout.Column = 5;

label = uilabel(layout,'Text','Injected contract fault', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 6;
faultMode = uidropdown(layout, ...
    'Items',{'None','Wrong interface ID','Unit mismatch', ...
    'Sequence out of range','Invalid quality code','Checksum corruption'}, ...
    'Value','None');
faultMode.ItemsData = {'none','identifier-mismatch','unit-mismatch', ...
    'sequence-out-of-range','quality-code-invalid','checksum-corruption'};
faultMode.Layout.Row = 4; faultMode.Layout.Column = 6;

label = uilabel(layout,'Text','Pre-transfer event', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 7;
eventMode = uidropdown(layout, ...
    'Items',{'None','Cancellation','Timeout','Cancel + timeout tie'}, ...
    'Value','None');
eventMode.ItemsData = { ...
    'none','cancellation','timeout','cancellation-timeout-tie'};
eventMode.Layout.Row = 4; eventMode.Layout.Column = 7;

label = uilabel(layout,'Text','Receiver validation', ...
    'HorizontalAlignment','center');
label.Layout.Row = 3; label.Layout.Column = 8;
validationMode = uidropdown(layout, ...
    'Items',{'Complete contract','Broken: value only'}, ...
    'Value','Complete contract');
validationMode.ItemsData = {'complete','value-only'};
validationMode.Layout.Row = 4; validationMode.Layout.Column = 8;

resetButton = uibutton(layout,'Text','Reset baseline');
resetButton.Layout.Row = 4; resetButton.Layout.Column = 9;

sourceAngle.ValueChangedFcn = @(~,~) updatePlots();
payloadWords.ValueChangedFcn = @(~,~) updatePlots();
senderVersion.ValueChangedFcn = @(~,~) updatePlots();
sequenceNumber.ValueChangedFcn = @(~,~) updatePlots();
sourceQuality.ValueChangedFcn = @(~,~) updatePlots();
faultMode.ValueChangedFcn = @(~,~) updatePlots();
eventMode.ValueChangedFcn = @(~,~) updatePlots();
validationMode.ValueChangedFcn = @(~,~) updatePlots();
resetButton.ButtonPushedFcn = @(~,~) resetBaseline();
updatePlots();

    function updatePlots
        out = modelFcn(sourceAngle.Value,payloadWords.Value, ...
            senderVersion.Value,sequenceNumber.Value,sourceQuality.Value, ...
            faultMode.Value,eventMode.Value,validationMode.Value);

        cla(clauseAxes);
        bar(clauseAxes,1:out.clauseCount,double(out.clausePass));
        grid(clauseAxes,'on'); ylim(clauseAxes,[0 1.2]);
        clauseAxes.XTick = 1:out.clauseCount;
        clauseAxes.XTickLabel = out.clauseNames;
        clauseAxes.XTickLabelRotation = 25;
        clauseAxes.YTick = [0 1];
        clauseAxes.YTickLabel = {'Fail / not evaluated','Pass'};
        xlabel(clauseAxes,'Interface Control Contract clause (-)');
        ylabel(clauseAxes,'Clause result (Boolean -)');
        title(clauseAxes, ...
            'Complete validation requires every producer-receiver agreement');

        cla(valueAxes);
        bar(valueAxes,1:2,[out.inputs.sourceAngleDeg,out.p06ObservedAngleDeg]);
        grid(valueAxes,'on');
        valueAxes.XTick = 1:2;
        valueAxes.XTickLabel = {'P07-qualified source', ...
            'Receiver-assumed P06 scalar'};
        valueAxes.XTickLabelRotation = 15;
        xlabel(valueAxes,'Comparable semantic endpoint (-)');
        ylabel(valueAxes,'Position interpreted as degrees (deg)');
        title(valueAxes, ...
            'Acceptance without unit agreement can release the wrong meaning');

        summary.Text = sprintf(['INTERFACE CONTROL CONTRACT\n\n' ...
            'required interface       %9d\ntransmitted interface    %9d\n' ...
            'required version         %9d\nsender version           %9d\n' ...
            'required payload         %9d word\ndeclared payload         %9d word\n' ...
            'expected unit            %9s\npayload unit             %9s\n' ...
            'source angle             %+9.6f deg\npayload numeric          %+9.6f %s\n' ...
            'contract range margin    %+9.6f deg\n' ...
            'receiver-assumed margin %+9.6f deg\nsequence                 %9d count\n' ...
            'quality code             %9d\nexpected checksum        %9d count\n' ...
            'transmitted checksum     %9d count\n\ntransfer attempted       %9d\n' ...
            'payload arrived          %9d\nclauses passed           %9d / %d\n' ...
            'contract conformant      %9d\nreceiver accepted        %9d\n' ...
            'contract input eligible  %9d\nreceiver input released  %9d\n' ...
            'false acceptance         %9d\nfalse release            %9d\n' ...
            'semantic error           %+9.6f deg\nmeaning preserved        %9d\n\n' ...
            'terminal                 %s\nfailure                  %s\n' ...
            'reporting failure        %s'], ...
            out.contractInterfaceId,out.transmittedInterfaceId, ...
            out.contractVersion,out.inputs.senderVersion, ...
            out.requiredPayloadWords,out.inputs.payloadWordCount, ...
            out.expectedUnit,out.payloadUnit,out.inputs.sourceAngleDeg, ...
            out.payloadAngleValue,out.payloadUnit,out.rangeMarginDeg, ...
            out.receiverAssumedRangeMarginDeg, ...
            out.transmittedSequence,out.wireQualityCode, ...
            out.checksumExpected,out.transmittedChecksum, ...
            out.transferAttempted,out.payloadArrived,sum(out.clausePass), ...
            out.clauseCount,out.contractConformant,out.receiverAccepted, ...
            out.contractInputEligible,out.receiverInputReleased, ...
            out.falseAcceptance,out.falseRelease,out.semanticErrorDeg, ...
            out.semanticValuePreserved,out.terminalStatus,out.failureMode, ...
            out.reportingFailureMode);
    end

    function resetBaseline
        sourceAngle.Value = 30.021978021978;
        payloadWords.Value = 6;
        senderVersion.Value = 1;
        sequenceNumber.Value = 42;
        sourceQuality.Value = true;
        faultMode.Value = 'none';
        eventMode.Value = 'none';
        validationMode.Value = 'complete';
        updatePlots();
    end
end
