function run_checks
%RUN_CHECKS Deterministic checks for the P08 Interface Control Contract.
baseline = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
assertContractInvariant(baseline);

expectedClauseNames = { ...
    'Interface identity', ...
    'Schema version', ...
    'Payload length', ...
    'Engineering unit', ...
    'Value range', ...
    'Sequence range', ...
    'Quality encoding', ...
    'Checksum integrity'};
expectedPayloadFieldNames = { ...
    'interface-id','schema-version','sequence','angle','quality','checksum'};
expectedPayloadFieldUnits = { ...
    '-','-','count','declared-unit','Boolean code','count'};
expectedEnvelopeMetadataNames = {'payload-word-count','engineering-unit'};
expectedEnvelopeMetadataUnits = {'word','text'};
assert(isequal(baseline.clauseNames,expectedClauseNames) && ...
    isequal(baseline.payloadFieldNames,expectedPayloadFieldNames) && ...
    isequal(baseline.payloadFieldUnits,expectedPayloadFieldUnits) && ...
    isequal(baseline.envelopeMetadataNames,expectedEnvelopeMetadataNames) && ...
    isequal(baseline.envelopeMetadataUnits,expectedEnvelopeMetadataUnits), ...
    'Clause, envelope metadata, and payload identity must remain explicit and ordered.');
assert(baseline.clauseCount == 8 && baseline.payloadFieldCount == 6 && ...
    baseline.envelopeMetadataCount == 2 && ...
    baseline.contractInterfaceId == 801 && baseline.contractVersion == 1 && ...
    baseline.requiredPayloadWords == 6 && ...
    strcmp(baseline.expectedUnit,'deg') && ...
    baseline.minimumAngleDeg == -180 && ...
    baseline.maximumAngleDeg == 180 && ...
    baseline.maximumPayloadWords == 16 && ...
    baseline.maximumVersion == 255 && ...
    baseline.maximumSequence == 65535 && ...
    baseline.checksumModulus == 65536, ...
    'The fixed Interface Control Contract resource envelope changed.');

independentChecksum = mod(801 + 1 + 6 + 42 + ...
    round(1000*30.021978021978) + 1 + 1,65536);
assert(independentChecksum == 30874 && ...
    baseline.checksumExpected == independentChecksum && ...
    baseline.transmittedChecksum == independentChecksum && ...
    isequal(baseline.payloadValues, ...
    [801 1 42 30.021978021978 1 independentChecksum]), ...
    'The baseline record must follow the transparent checksum equation.');
assert(all(baseline.clauseEvaluated) && all(baseline.clausePass) && ...
    baseline.transferAttempted && baseline.payloadArrived && ...
    baseline.contractConformant && baseline.receiverValuePlausible && ...
    baseline.receiverAccepted && baseline.receiverDecisionCorrect && ...
    baseline.contractInputEligible && baseline.receiverInputReleased && ...
    ~baseline.falseAcceptance && ~baseline.falseRelease && ...
    baseline.p06ObservedAngleDeg == baseline.inputs.sourceAngleDeg && ...
    baseline.semanticErrorDeg == 0 && baseline.semanticValuePreserved && ...
    baseline.p07QualityPreserved && baseline.p06ScalarContractMet && ...
    baseline.rangeMarginDeg > 149 && ...
    baseline.receiverAssumedRangeMarginDeg == baseline.rangeMarginDeg && ...
    strcmp(baseline.terminalStatus,'accepted-and-released') && ...
    strcmp(baseline.failureMode,'none') && ...
    strcmp(baseline.reportingFailureMode,'none'), ...
    'The complete baseline must accept and release one unchanged scalar.');

negativeLimit = model(-180,6,1,42,true,'none','none','complete');
positiveLimit = model(180,6,1,42,true,'none','none','complete');
zeroAngle = model(0,6,1,42,true,'none','none','complete');
negativeJustOutside = model(-180.001,6,1,42,true, ...
    'none','none','complete');
positiveJustOutside = model(180.001,6,1,42,true, ...
    'none','none','complete');
negativeMaximum = model(-360,6,1,42,true,'none','none','complete');
positiveMaximum = model(360,6,1,42,true,'none','none','complete');
for candidate = {negativeLimit,positiveLimit,zeroAngle, ...
        negativeJustOutside,positiveJustOutside,negativeMaximum,positiveMaximum}
    assertContractInvariant(candidate{1});
end
assert(negativeLimit.rangeMatches && negativeLimit.rangeMarginDeg == 0 && ...
    negativeLimit.receiverInputReleased && ...
    positiveLimit.rangeMatches && positiveLimit.rangeMarginDeg == 0 && ...
    positiveLimit.receiverInputReleased && zeroAngle.rangeMarginDeg == 180, ...
    'Signed zero and exact +/-180 deg limits must be accepted inclusively.');
for candidate = {negativeJustOutside,positiveJustOutside, ...
        negativeMaximum,positiveMaximum}
    assert(~candidate{1}.rangeMatches && ...
        ~candidate{1}.contractConformant && ...
        ~candidate{1}.receiverAccepted && ...
        ~candidate{1}.receiverInputReleased && ...
        candidate{1}.rangeMarginDeg < 0 && ...
        strcmp(candidate{1}.terminalStatus,'rejected') && ...
        strcmp(candidate{1}.failureMode,'angle-out-of-range'), ...
        'Every bounded source outside the receiver envelope must be rejected.');
end

payloadWordChoices = 0:16;
for wordCount = payloadWordChoices
    candidate = model(30.021978021978,wordCount,1,42,true, ...
        'none','none','complete');
    assertContractInvariant(candidate);
    assert(candidate.lengthMatches == (wordCount == 6) && ...
        candidate.receiverAccepted == (wordCount == 6) && ...
        candidate.receiverInputReleased == (wordCount == 6), ...
        'Only the exact required payload length may pass.');
end
minimumPayload = model(30.021978021978,0,1,42,true, ...
    'none','none','complete');
maximumPayload = model(30.021978021978,16,1,42,true, ...
    'none','none','complete');
assert(~minimumPayload.lengthMatches && ~maximumPayload.lengthMatches && ...
    minimumPayload.inputs.payloadWordCount == 0 && ...
    maximumPayload.inputs.payloadWordCount == 16, ...
    'Payload bounds must be representable without being called compatible.');

minimumVersion = model(30.021978021978,6,0,42,true, ...
    'none','none','complete');
supportedVersion = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
nextVersion = model(30.021978021978,6,2,42,true, ...
    'none','none','complete');
maximumVersion = model(30.021978021978,6,255,42,true, ...
    'none','none','complete');
for candidate = {minimumVersion,supportedVersion,nextVersion,maximumVersion}
    assertContractInvariant(candidate{1});
end
assert(~minimumVersion.versionMatches && ...
    strcmp(minimumVersion.failureMode,'version-mismatch') && ...
    supportedVersion.versionMatches && supportedVersion.receiverAccepted && ...
    ~nextVersion.versionMatches && ~nextVersion.receiverAccepted && ...
    ~maximumVersion.versionMatches, ...
    'Compatibility must be explicit equality with schema version 1.');

minimumSequence = model(30.021978021978,6,1,0,true, ...
    'none','none','complete');
maximumSequence = model(30.021978021978,6,1,65535,true, ...
    'none','none','complete');
sequenceOutOfRange = model(30.021978021978,6,1,42,true, ...
    'sequence-out-of-range','none','complete');
for candidate = {minimumSequence,maximumSequence,sequenceOutOfRange}
    assertContractInvariant(candidate{1});
end
assert(minimumSequence.sequenceMatches && minimumSequence.receiverAccepted && ...
    maximumSequence.sequenceMatches && maximumSequence.receiverAccepted && ...
    sequenceOutOfRange.transmittedSequence == 65536 && ...
    ~sequenceOutOfRange.sequenceMatches && ...
    strcmp(sequenceOutOfRange.failureMode,'sequence-out-of-range'), ...
    'Sequence endpoints must be inclusive and injected overflow must fail.');

wrongIdentity = model(30.021978021978,6,1,42,true, ...
    'identifier-mismatch','none','complete');
wrongUnit = model(30.021978021978,6,1,42,true, ...
    'unit-mismatch','none','complete');
invalidQualityCode = model(30.021978021978,6,1,42,true, ...
    'quality-code-invalid','none','complete');
corruptedChecksum = model(30.021978021978,6,1,42,true, ...
    'checksum-corruption','none','complete');
for candidate = {wrongIdentity,wrongUnit,invalidQualityCode,corruptedChecksum}
    assertContractInvariant(candidate{1});
    assert(~candidate{1}.contractConformant && ...
        ~candidate{1}.receiverAccepted && ...
        ~candidate{1}.receiverInputReleased && ...
        strcmp(candidate{1}.terminalStatus,'rejected'), ...
        'Every injected clause failure must be rejected by complete validation.');
end
assert(wrongIdentity.transmittedInterfaceId == 802 && ...
    ~wrongIdentity.identityMatches && ...
    strcmp(wrongIdentity.failureMode,'identifier-mismatch'), ...
    'A record for another interface must fail identity.');
assert(strcmp(wrongUnit.payloadUnit,'rad') && ~wrongUnit.unitMatches && ...
    ~wrongUnit.rangeMatches && wrongUnit.receiverAssumedRangeMatches && ...
    isnan(wrongUnit.rangeMarginDeg) && ...
    wrongUnit.receiverAssumedRangeMarginDeg > 179 && ...
    abs(wrongUnit.payloadAngleValue - ...
    30.021978021978*pi/180) < 1e-12 && ...
    strcmp(wrongUnit.failureMode,'unit-mismatch'), ...
    'A radians producer must not satisfy a degrees receiver contract.');
assert(invalidQualityCode.wireQualityCode == 2 && ...
    ~invalidQualityCode.qualityEncodingMatches && ...
    ~invalidQualityCode.p07QualityPreserved && ...
    strcmp(invalidQualityCode.failureMode,'quality-code-invalid'), ...
    'Undefined quality encoding must be rejected rather than guessed.');
assert(corruptedChecksum.transmittedChecksum == ...
    mod(corruptedChecksum.checksumExpected + 1,65536) && ...
    ~corruptedChecksum.checksumMatches && ...
    strcmp(corruptedChecksum.failureMode,'checksum-mismatch'), ...
    'A one-count integrity corruption must be visible.');

qualityWithheld = model(30.021978021978,6,1,42,false, ...
    'none','none','complete');
assertContractInvariant(qualityWithheld);
assert(qualityWithheld.qualityEncodingMatches && ...
    qualityWithheld.p07QualityPreserved && ...
    qualityWithheld.contractConformant && ...
    qualityWithheld.receiverAccepted && ...
    ~qualityWithheld.contractInputEligible && ...
    ~qualityWithheld.receiverInputReleased && ...
    isnan(qualityWithheld.p06ObservedAngleDeg) && ...
    strcmp(qualityWithheld.terminalStatus,'accepted-quality-withheld') && ...
    strcmp(qualityWithheld.failureMode,'source-quality-invalid'), ...
    'Legal invalid quality must preserve the record while withholding P06 input.');

cancelled = model(30.021978021978,6,1,42,true, ...
    'none','cancellation','complete');
timedOut = model(30.021978021978,6,1,42,true, ...
    'none','timeout','complete');
tied = model(30.021978021978,6,1,42,true, ...
    'none','cancellation-timeout-tie','complete');
eventBeforeMismatch = model(30.021978021978,5,0,42,true, ...
    'checksum-corruption','timeout','complete');
for candidate = {cancelled,timedOut,tied,eventBeforeMismatch}
    assertContractInvariant(candidate{1});
    assert(candidate{1}.eventObserved && ...
        ~candidate{1}.transferAttempted && ...
        ~candidate{1}.payloadArrived && ...
        ~any(candidate{1}.clauseEvaluated) && ...
        ~any(candidate{1}.clausePass) && ...
        ~candidate{1}.contractConformant && ...
        ~candidate{1}.receiverAccepted && ...
        ~candidate{1}.receiverDecisionCorrect && ...
        ~candidate{1}.receiverInputReleased && ...
        isnan(candidate{1}.p06ObservedAngleDeg) && ...
        candidate{1}.terminalOutcomeHandled, ...
        'A pre-transfer event must isolate every receiver-side decision.');
end
assert(cancelled.cancellationObserved && ~cancelled.timeoutObserved && ...
    strcmp(cancelled.terminalStatus,'cancelled') && ...
    strcmp(cancelled.failureMode,'transfer-cancelled'), ...
    'Cancellation must remain distinguishable from timeout.');
assert(~timedOut.cancellationObserved && timedOut.timeoutObserved && ...
    strcmp(timedOut.terminalStatus,'timed-out') && ...
    strcmp(timedOut.failureMode,'transfer-timeout'), ...
    'Timeout must remain an asserted guard, not measured time.');
assert(tied.cancellationObserved && tied.timeoutObserved && ...
    tied.tieResolvedToCancellation && strcmp(tied.terminalStatus,'cancelled'), ...
    'Cancellation must retain inherited precedence in the injected tie.');
assert(strcmp(eventBeforeMismatch.failureMode,'transfer-timeout'), ...
    'A pre-transfer timeout must precede all payload mismatch diagnoses.');

brokenIdentity = model(30.021978021978,6,1,42,true, ...
    'identifier-mismatch','none','value-only');
brokenUnit = model(30.021978021978,6,1,42,true, ...
    'unit-mismatch','none','value-only');
brokenVersion = model(30.021978021978,6,2,42,true, ...
    'none','none','value-only');
brokenLength = model(30.021978021978,5,1,42,true, ...
    'none','none','value-only');
brokenSequence = model(30.021978021978,6,1,42,true, ...
    'sequence-out-of-range','none','value-only');
brokenChecksum = model(30.021978021978,6,1,42,true, ...
    'checksum-corruption','none','value-only');
brokenQualityEncoding = model(30.021978021978,6,1,42,true, ...
    'quality-code-invalid','none','value-only');
for candidate = {brokenIdentity,brokenVersion,brokenLength,brokenUnit, ...
        brokenSequence,brokenQualityEncoding,brokenChecksum}
    assertContractInvariant(candidate{1});
    assert(candidate{1}.receiverValuePlausible && ...
        ~candidate{1}.contractConformant && ...
        candidate{1}.receiverAccepted && ...
        candidate{1}.receiverInputReleased && ...
        candidate{1}.falseAcceptance && candidate{1}.falseRelease && ...
        ~candidate{1}.receiverDecisionCorrect && ...
        strcmp(candidate{1}.reportingFailureMode, ...
        'value-only-false-acceptance'), ...
        'Value-only validation must expose false acceptance for every ignored clause.');
end
assert(~brokenUnit.semanticValuePreserved && ...
    abs(brokenUnit.semanticErrorDeg - ...
    (30.021978021978*pi/180 - 30.021978021978)) < 1e-12 && ...
    ~brokenUnit.p06ScalarContractMet, ...
    'The unit mismatch must expose the expected semantic error.');

brokenQuality = model(30.021978021978,6,1,42,false, ...
    'none','none','value-only');
assertContractInvariant(brokenQuality);
assert(brokenQuality.contractConformant && brokenQuality.receiverAccepted && ...
    brokenQuality.receiverInputReleased && ...
    ~brokenQuality.contractInputEligible && ...
    ~brokenQuality.falseAcceptance && brokenQuality.falseRelease && ...
    brokenQuality.receiverDecisionCorrect && ...
    strcmp(brokenQuality.reportingFailureMode,'value-only-false-release'), ...
    'Value-only validation must expose release of a conformant invalid-quality record.');
brokenOutOfRange = model(180.001,6,1,42,true, ...
    'none','none','value-only');
assertContractInvariant(brokenOutOfRange);
assert(~brokenOutOfRange.receiverValuePlausible && ...
    ~brokenOutOfRange.receiverAccepted && ...
    ~brokenOutOfRange.falseAcceptance && ...
    ~brokenOutOfRange.receiverInputReleased, ...
    'Value-only validation still rejects a number outside its sole range check.');

compatible = model(int16(30),uint8(6),uint8(1),uint16(42),uint8(1), ...
    string(' NONE '),string(' NONE '),string(' COMPLETE '));
compatibleReference = model(30,6,1,42,true,'none','none','complete');
assert(isequaln(compatible,compatibleReference), ...
    'Compatible numeric scalar and scalar-text classes must normalize identically.');

expectErrorId(@() model(NaN,6,1,42,true,'none','none','complete'), ...
    'P08:InvalidAngle');
expectAnyError(@() model(Inf,6,1,42,true,'none','none','complete'));
expectAnyError(@() model(1+1i,6,1,42,true,'none','none','complete'));
expectAnyError(@() model([30 31],6,1,42,true,'none','none','complete'));
expectAnyError(@() model('30',6,1,42,true,'none','none','complete'));
expectAnyError(@() model(360.001,6,1,42,true,'none','none','complete'));
expectAnyError(@() model(-360.001,6,1,42,true,'none','none','complete'));
expectErrorId(@() model(30,-1,1,42,true,'none','none','complete'), ...
    'P08:InvalidPayloadWordCount');
expectAnyError(@() model(30,17,1,42,true,'none','none','complete'));
expectAnyError(@() model(30,6.5,1,42,true,'none','none','complete'));
expectAnyError(@() model(30,[5 6],1,42,true,'none','none','complete'));
expectErrorId(@() model(30,6,-1,42,true,'none','none','complete'), ...
    'P08:InvalidSenderVersion');
expectAnyError(@() model(30,6,256,42,true,'none','none','complete'));
expectAnyError(@() model(30,6,1.5,42,true,'none','none','complete'));
expectErrorId(@() model(30,6,1,-1,true,'none','none','complete'), ...
    'P08:InvalidSequence');
expectAnyError(@() model(30,6,1,65536,true,'none','none','complete'));
expectAnyError(@() model(30,6,1,42.5,true,'none','none','complete'));
expectErrorId(@() model(30,6,1,42,2,'none','none','complete'), ...
    'P08:InvalidQuality');
expectAnyError(@() model(30,6,1,42,[true false], ...
    'none','none','complete'));
expectAnyError(@() model(30,6,1,42,'true','none','none','complete'));
expectErrorId(@() model(30,6,1,42,true,'wire-break','none','complete'), ...
    'P08:InvalidFaultMode');
expectErrorId(@() model(30,6,1,42,true,'none','deadline','complete'), ...
    'P08:InvalidEventMode');
expectErrorId(@() model(30,6,1,42,true,'none','none','trust-me'), ...
    'P08:InvalidValidationMode');
expectAnyError(@() model(30,6,1,42,true, ...
    string({'none','unit-mismatch'}),'none','complete'));
expectAnyError(@() model(30,6,1,42,true,1,'none','complete'));

afterMalformed = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterRange = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterLength = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterVersion = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterFault = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterCancellation = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterTimeout = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
afterBroken = model(30.021978021978,6,1,42,true, ...
    'none','none','complete');
assert(isequaln(afterMalformed,baseline) && isequaln(afterRange,baseline) && ...
    isequaln(afterLength,baseline) && isequaln(afterVersion,baseline) && ...
    isequaln(afterFault,baseline) && ...
    isequaln(afterCancellation,baseline) && ...
    isequaln(afterTimeout,baseline) && isequaln(afterBroken,baseline), ...
    'Calls after malformed, rejected, guarded, or broken cases must recover exactly.');
disp('P08 checks passed: clauses, ranges, compatibility, guards, recovery, and isolation.');
end

function assertContractInvariant(out)
assert(out.clauseCount == 8 && out.payloadFieldCount == 6 && ...
    out.envelopeMetadataCount == 2 && ...
    isequal(size(out.clauseEvaluated),[1 8]) && ...
    isequal(size(out.clausePass),[1 8]) && ...
    isequal(size(out.payloadValues),[1 6]), ...
    'Every result must stay inside the fixed clause and payload envelope.');
assert(out.eventObserved == ...
    (out.cancellationObserved || out.timeoutObserved) && ...
    out.transferAttempted == ~out.eventObserved && ...
    out.payloadArrived == out.transferAttempted, ...
    'Transfer reachability must derive only from the asserted event guard.');
if out.transferAttempted
    visibleClausePass = [out.identityMatches out.versionMatches ...
        out.lengthMatches out.unitMatches out.rangeMatches ...
        out.sequenceMatches out.qualityEncodingMatches out.checksumMatches];
    assert(all(out.clauseEvaluated) && ...
        isequal(out.clausePass,visibleClausePass) && ...
        isfinite(out.receiverAssumedRangeMarginDeg), ...
        'An arrived record must evaluate every clause exactly once.');
else
    assert(~any(out.clauseEvaluated) && ~any(out.clausePass) && ...
        ~out.identityMatches && ~out.versionMatches && ...
        ~out.lengthMatches && ~out.unitMatches && ~out.rangeMatches && ...
        ~out.receiverAssumedRangeMatches && ~out.sequenceMatches && ...
        ~out.qualityEncodingMatches && ~out.checksumMatches && ...
        isnan(out.rangeMarginDeg) && ...
        isnan(out.receiverAssumedRangeMarginDeg), ...
        'A blocked transfer must expose no receiver-side clause result.');
end
assert(out.contractConformant == ...
    (out.transferAttempted && all(out.clausePass)) && ...
    out.receiverValuePlausible == ...
    (out.transferAttempted && isfinite(out.payloadAngleValue) && ...
    out.receiverAssumedRangeMatches), ...
    'Conformance and value-only plausibility must remain separate equations.');
if out.transferAttempted && out.unitMatches
    assert(out.rangeMarginDeg == out.receiverAssumedRangeMarginDeg, ...
        'A matching degree unit must expose the factual degree range margin.');
else
    assert(isnan(out.rangeMarginDeg), ...
        'A missing or mismatched unit must expose no factual degree margin.');
end
assert(out.contractInputEligible == ...
    (out.contractConformant && out.wireQualityCode == 1) && ...
    out.falseAcceptance == ...
    (out.receiverAccepted && ~out.contractConformant) && ...
    out.falseRelease == ...
    (out.receiverInputReleased && ~out.contractInputEligible) && ...
    out.receiverDecisionCorrect == ...
    (out.transferAttempted && ...
    (out.receiverAccepted == out.contractConformant)), ...
    'Receiver decisions must remain traceable to complete contract truth.');
if strcmp(out.inputs.validationMode,'complete')
    assert(out.receiverAccepted == out.contractConformant && ...
        out.receiverInputReleased == out.contractInputEligible, ...
        'Complete validation must follow conformance and quality exactly.');
else
    assert(out.receiverAccepted == out.receiverValuePlausible && ...
        out.receiverInputReleased == out.receiverAccepted, ...
        'Value-only validation must use only finite in-range magnitude.');
end
if out.receiverInputReleased
    assert(isfinite(out.p06ObservedAngleDeg) && ...
        out.p06ObservedAngleDeg == out.payloadAngleValue && ...
        out.semanticErrorDeg == ...
        out.p06ObservedAngleDeg - out.inputs.sourceAngleDeg, ...
        'A released scalar must expose its assumed degree value and semantic error.');
else
    assert(isnan(out.p06ObservedAngleDeg) && isnan(out.semanticErrorDeg) && ...
        ~out.semanticValuePreserved, ...
        'A withheld scalar must expose no receiver value or semantic claim.');
end
assert(out.transmittedChecksum >= 0 && ...
    out.transmittedChecksum < out.checksumModulus && ...
    out.checksumExpected >= 0 && ...
    out.checksumExpected < out.checksumModulus && ...
    out.terminalOutcomeHandled, ...
    'Checksum values and terminal handling must stay bounded.');
if out.eventObserved
    assert(~out.receiverAccepted && ~out.receiverInputReleased && ...
        ~out.receiverDecisionCorrect && isnan(out.p06ObservedAngleDeg), ...
        'A guarded transfer cannot produce a receiver decision or scalar.');
end
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
