function run_checks()
%RUN_CHECKS Independent state, transition, rollback, and recovery checks.

baseline = model(2,2,true,true,'nominal','none','guarded-priority');
assertStateMachineInvariant(baseline);

expectedStateNames = {'OFF','STANDBY','READY','ACTIVE','FAULT','SAFE-HOLD'};
expectedEventNames = {'enter-standby-request','readiness-evidence', ...
    'readiness-evidence','readiness-evidence','readiness-evidence', ...
    'activate-request','operate','operate','operate','operate','operate', ...
    'stop-request','off-request'};
expectedRollbackEventNames = {'enter-safe-hold', ...
    'clear-transition-requests','return-off-after-p09-proof'};
expectedTransitionInputNames = {'enter-standby-request', ...
    'readiness-evidence','activate-request','operate','feedback-loss', ...
    'reset-request','recovery-evidence','stop-request','off-request'};
expectedTransitionTable = logical([ ...
    1 1 0 0 0 0; ...
    0 1 1 0 0 1; ...
    0 0 1 1 0 1; ...
    0 0 0 1 1 1; ...
    0 0 1 0 1 1; ...
    1 0 0 0 0 1]);
expectedBaselineTrace = [2 2 3 3 3 4 4 4 4 4 4 6 1];
expectedBaselineSources = [1 2 2 3 3 3 4 4 4 4 4 4 6];
expectedBaselineInputs = false(13,9);
expectedBaselineInputs(1,1) = true;
expectedBaselineInputs(2:5,2) = true;
expectedBaselineInputs(6,3) = true;
expectedBaselineInputs(7:11,4) = true;
expectedBaselineInputs(12,8) = true;
expectedBaselineInputs(13,9) = true;

assert(isequal(baseline.stateNames,expectedStateNames) && ...
    isequal(baseline.eventNames,expectedEventNames) && ...
    isequal(baseline.rollbackEventNames,expectedRollbackEventNames) && ...
    isequal(baseline.transitionInputNames,expectedTransitionInputNames), ...
    'The fixed P10 state, event, rollback, or input identity changed.');
assert(isequal(baseline.transitionTable,expectedTransitionTable) && ...
    isequal(baseline.stateIdTrace,expectedBaselineTrace) && ...
    isequal(baseline.sourceStateId,expectedBaselineSources) && ...
    isequal(baseline.observedStateId,expectedBaselineTrace), ...
    'The baseline recurrence or transition table changed.');
assert(isequal(baseline.transitionInputMatrix,expectedBaselineInputs) && ...
    isequal(baseline.transitionInputCount,ones(1,13)) && ...
    ~any(baseline.transitionInputConflict), ...
    'The baseline raw input inventory changed.');
assert(all(baseline.transitionEvaluated) && ...
    all(baseline.transitionTableAllowed) && ...
    all(baseline.reportedTransitionTableAllowed) && ...
    all(baseline.strictGuardPass) && ...
    all(baseline.reportedGuardPass) && ...
    all(baseline.strictPostconditionPass) && ...
    all(baseline.reportedPostconditionPass) && ...
    all(baseline.strictTransitionPass) && ...
    all(baseline.reportedTransitionPass) && ...
    all(baseline.policyStepAccepted) && ...
    ~any(baseline.transitionHazard) && ...
    ~any(baseline.priorityViolation) && ~any(baseline.guardBypassed), ...
    'Every baseline transition must prove edge, guard, and effect.');
assert(isequal(baseline.stateObservationCount,[1 2 3 6 0 1]) && ...
    baseline.stateChangeCount == 5 && ...
    baseline.readinessEvidenceCount == 2 && ...
    baseline.readinessQualifiedStep == 3 && ...
    baseline.recoveryEvidenceCount == 0 && ...
    isnan(baseline.recoveryQualifiedStep) && ...
    baseline.sequenceCompleted && baseline.sequenceFinalStateId == 1 && ...
    baseline.strictStateMachineAccepted && ...
    baseline.reportedStateMachineAccepted && ...
    baseline.assessmentDecisionCorrect && ~baseline.falseApproval && ...
    baseline.totalViolationCount == 0 && ...
    strcmp(baseline.terminalStatus,'completed-off') && ...
    strcmp(baseline.failureMode,'none'), ...
    'Baseline acceptance, counts, or terminal status changed.');

readinessReadySteps = zeros(1,4);
readinessStandbyObservations = zeros(1,4);
for confirmations = 1:4
    candidate = model(confirmations,2,true,true, ...
        'nominal','none','guarded-priority');
    assertStateMachineInvariant(candidate);
    readinessReadySteps(confirmations) = candidate.readinessQualifiedStep;
    readinessStandbyObservations(confirmations) = ...
        candidate.stateObservationCount(2);
    assert(candidate.strictStateMachineAccepted && ...
        candidate.inputs.readinessConfirmations == confirmations && ...
        candidate.inputs.recoveryConfirmations == 2, ...
        'Readiness sweep must isolate the readiness confirmation lever.');
end
readinessMinimum = model(1,2,true,true, ...
    'nominal','none','guarded-priority');
readinessMaximum = model(4,2,true,true, ...
    'nominal','none','guarded-priority');
assert(isequal(readinessReadySteps,[2 3 4 5]) && ...
    isequal(readinessStandbyObservations,[1 2 3 4]) && ...
    readinessMinimum.readinessQualifiedStep == 2 && ...
    readinessMaximum.readinessQualifiedStep == 5, ...
    'Readiness limiting cases or monotonic response changed.');

recoveryReadySteps = zeros(1,4);
recoveryFaultObservations = zeros(1,4);
for confirmations = 1:4
    candidate = model(2,confirmations,true,true, ...
        'recoverable-feedback-loss','none','guarded-priority');
    assertStateMachineInvariant(candidate);
    recoveryReadySteps(confirmations) = candidate.recoveryQualifiedStep;
    recoveryFaultObservations(confirmations) = ...
        candidate.stateObservationCount(5);
    assert(candidate.strictStateMachineAccepted && ...
        candidate.inputs.readinessConfirmations == 2 && ...
        candidate.inputs.recoveryConfirmations == confirmations, ...
        'Recovery sweep must isolate the recovery confirmation lever.');
end
recoveryMinimum = model(2,1,true,true, ...
    'recoverable-feedback-loss','none','guarded-priority');
recoveryMaximum = model(2,4,true,true, ...
    'recoverable-feedback-loss','none','guarded-priority');
expectedRecoverableTrace = [2 2 3 3 3 4 5 5 3 3 3 6 1];
recoverable = model(2,2,true,true, ...
    'recoverable-feedback-loss','none','guarded-priority');
assertStateMachineInvariant(recoverable);
assert(isequal(recoveryReadySteps,[8 9 10 11]) && ...
    isequal(recoveryFaultObservations,[1 2 3 4]) && ...
    recoveryMinimum.recoveryQualifiedStep == 8 && ...
    recoveryMaximum.recoveryQualifiedStep == 11 && ...
    isequal(recoverable.stateIdTrace,expectedRecoverableTrace) && ...
    recoverable.recoveryEvidenceCount == 2 && ...
    recoverable.strictStateMachineAccepted, ...
    'Recoverable-fault recurrence or limiting cases changed.');

startupProofMissing = model(2,2,false,true, ...
    'nominal','none','guarded-priority');
safeOffProofMissing = model(2,2,true,false, ...
    'nominal','none','guarded-priority');
prematureActivation = model(2,2,true,true, ...
    'premature-activation','none','guarded-priority');
stuckState = model(2,2,true,true, ...
    'state-stuck-active','none','guarded-priority');
for candidate = {startupProofMissing,safeOffProofMissing, ...
        prematureActivation,stuckState}
    assertStateMachineInvariant(candidate{1});
    assert(~candidate{1}.strictStateMachineAccepted && ...
        ~candidate{1}.reportedStateMachineAccepted && ...
        strcmp(candidate{1}.terminalStatus,'rejected-transition') && ...
        candidate{1}.terminalOutcomeHandled, ...
        'Every rejected negative case must have a handled terminal.');
end
assert(isequal(startupProofMissing.transitionEvaluated, ...
    [true false false false false false false false false false false false false]) && ...
    startupProofMissing.sourceStateId(1) == 1 && ...
    startupProofMissing.strictRequestedStateId(1) == 2 && ...
    startupProofMissing.observedStateId(1) == 1 && ...
    startupProofMissing.transitionTableAllowed(1) && ...
    ~startupProofMissing.strictGuardPass(1) && ...
    ~startupProofMissing.strictPostconditionPass(1) && ...
    startupProofMissing.firstViolationStep == 1 && ...
    strcmp(startupProofMissing.failureMode, ...
    'p09-startup-proof-unavailable'), ...
    'A missing composite P09 startup proof must reject OFF to STANDBY.');
assert(all(safeOffProofMissing.transitionEvaluated) && ...
    safeOffProofMissing.sourceStateId(13) == 6 && ...
    safeOffProofMissing.strictRequestedStateId(13) == 1 && ...
    safeOffProofMissing.observedStateId(13) == 6 && ...
    safeOffProofMissing.transitionTableAllowed(13) && ...
    ~safeOffProofMissing.strictGuardPass(13) && ...
    ~safeOffProofMissing.strictPostconditionPass(13) && ...
    safeOffProofMissing.firstViolationStep == 13 && ...
    strcmp(safeOffProofMissing.failureMode, ...
    'p09-safe-off-proof-unavailable'), ...
    'A missing composite P09 safe-off proof must retain SAFE-HOLD.');
assert(isequal(prematureActivation.transitionEvaluated, ...
    [true true false false false false false false false false false false false]) && ...
    prematureActivation.sourceStateId(2) == 2 && ...
    prematureActivation.strictRequestedStateId(2) == 4 && ...
    prematureActivation.observedStateId(2) == 2 && ...
    ~prematureActivation.transitionTableAllowed(2) && ...
    ~prematureActivation.strictGuardPass(2) && ...
    ~prematureActivation.strictPostconditionPass(2) && ...
    prematureActivation.firstViolationStep == 2 && ...
    strcmp(prematureActivation.failureMode,'activation-before-ready'), ...
    'Premature activation must fail edge, guard, and postcondition.');
assert(isequal(stuckState.transitionEvaluated, ...
    [true true true true true true true false false false false false false]) && ...
    stuckState.sourceStateId(7) == 4 && ...
    stuckState.strictRequestedStateId(7) == 5 && ...
    stuckState.observedStateId(7) == 4 && ...
    stuckState.transitionTableAllowed(7) && ...
    stuckState.strictGuardPass(7) && ...
    ~stuckState.strictPostconditionPass(7) && ...
    stuckState.firstViolationStep == 7 && ...
    strcmp(stuckState.failureMode,'state-postcondition-failed'), ...
    'A stuck state must fail only the observed postcondition at step 7.');

cancelled = model(2,2,true,true, ...
    'nominal','cancellation','guarded-priority');
timedOut = model(2,2,true,true, ...
    'nominal','timeout','guarded-priority');
tied = model(2,2,true,true, ...
    'nominal','cancellation-timeout-tie','guarded-priority');
expectedEvaluatedBeforeEvent = [true true true true true ...
    false false false false false false false false];
expectedRollbackTrace = [0 0 0 0 0 1; 0 0 0 0 0 1; 1 0 0 0 0 0];
for candidate = {cancelled,timedOut,tied}
    out = candidate{1};
    assertStateMachineInvariant(out);
    assert(isequal(out.transitionEvaluated,expectedEvaluatedBeforeEvent) && ...
        all(isfinite(out.stateIdTrace(1:5))) && ...
        all(isnan(out.stateIdTrace(6:13))) && ...
        isnan(out.sequenceFinalStateId) && ...
        out.eventObserved && out.rollbackPerformed && ...
        out.rollbackComplete && all(out.rollbackTransitionExecuted) && ...
        all(out.rollbackTransitionTableAllowed) && ...
        all(out.rollbackGuardPass) && ...
        all(out.rollbackPostconditionPass) && ...
        all(out.rollbackTransitionPass) && ...
        ~any(out.rollbackHazard) && ...
        isequal(out.rollbackStateTrace,expectedRollbackTrace) && ...
        out.rollbackFinalStateId == 1 && ...
        strcmp(out.preemptedTransitionInput,'activate-request') && ...
        strcmp(out.rollbackFailureMode,'none') && ...
        out.terminalOutcomeHandled, ...
        'An interruption must mask nominal facts and complete rollback.');
end
assert(cancelled.cancellationObserved && ~cancelled.timeoutObserved && ...
    strcmp(cancelled.observedInterruptionName,'cancellation') && ...
    strcmp(cancelled.terminalStatus,'cancelled-rollback-complete') && ...
    strcmp(cancelled.failureMode,'state-transition-cancelled'), ...
    'Cancellation must remain distinguishable and complete rollback.');
assert(~timedOut.cancellationObserved && timedOut.timeoutObserved && ...
    strcmp(timedOut.observedInterruptionName,'timeout') && ...
    strcmp(timedOut.terminalStatus,'timed-out-rollback-complete') && ...
    strcmp(timedOut.failureMode,'state-transition-timeout'), ...
    'Timeout must remain distinguishable and complete rollback.');
assert(tied.cancellationObserved && tied.timeoutObserved && ...
    tied.tieResolvedToCancellation && ...
    strcmp(tied.observedInterruptionName,'cancellation-timeout-tie') && ...
    strcmp(tied.terminalStatus,'cancelled-rollback-complete') && ...
    strcmp(tied.failureMode,'state-transition-cancelled'), ...
    'Cancellation must win the modeled cancellation/timeout tie.');

cancelledIncomplete = model(2,2,true,false, ...
    'nominal','cancellation','guarded-priority');
timedOutIncomplete = model(2,2,true,false, ...
    'nominal','timeout','guarded-priority');
tiedIncomplete = model(2,2,true,false, ...
    'nominal','cancellation-timeout-tie','guarded-priority');
for candidate = {cancelledIncomplete,timedOutIncomplete,tiedIncomplete}
    out = candidate{1};
    assertStateMachineInvariant(out);
    assert(out.rollbackPerformed && ~out.rollbackComplete && ...
        all(out.rollbackTransitionExecuted) && ...
        all(out.rollbackTransitionTableAllowed) && ...
        isequal(out.rollbackGuardPass,[true true false]) && ...
        isequal(out.rollbackPostconditionPass,[true true false]) && ...
        isequal(out.rollbackTransitionPass,[true true false]) && ...
        isequal(out.rollbackHazard,[false false true]) && ...
        isequal(out.rollbackObservedStateId,[6 6 6]) && ...
        out.rollbackFinalStateId == 6 && ...
        out.rollbackViolationCount == 1 && ...
        strcmp(out.rollbackFailureMode, ...
        'p09-safe-off-proof-unavailable'), ...
        'A missing P09 safe-off proof must expose incomplete rollback.');
end
assert(strcmp(cancelledIncomplete.terminalStatus, ...
    'cancelled-rollback-incomplete') && ...
    strcmp(timedOutIncomplete.terminalStatus, ...
    'timed-out-rollback-incomplete') && ...
    tiedIncomplete.tieResolvedToCancellation && ...
    strcmp(tiedIncomplete.terminalStatus, ...
    'cancelled-rollback-incomplete'), ...
    'Incomplete rollback must retain cancellation/timeout terminal truth.');

strictConflict = model(2,2,true,true, ...
    'fault-reset-conflict','none','guarded-priority');
broken = model(2,2,true,true, ...
    'fault-reset-conflict','none','last-request-wins');
strictConflictWithoutSafeOff = model(2,2,true,false, ...
    'fault-reset-conflict','none','guarded-priority');
brokenWithoutSafeOff = model(2,2,true,false, ...
    'fault-reset-conflict','none','last-request-wins');
assertStateMachineInvariant(strictConflict);
assertStateMachineInvariant(broken);
assertStateMachineInvariant(strictConflictWithoutSafeOff);
assertStateMachineInvariant(brokenWithoutSafeOff);
assert(isequal(strictConflict.transitionInputMatrix, ...
    broken.transitionInputMatrix) && ...
    strictConflict.transitionInputCount(7) == 2 && ...
    broken.transitionInputCount(7) == 2 && ...
    strictConflict.transitionInputConflict(7) && ...
    broken.transitionInputConflict(7) && ...
    strcmp(strictConflict.strictSelectedInput{7},'feedback-loss') && ...
    strcmp(strictConflict.reportedSelectedInput{7},'feedback-loss') && ...
    strcmp(broken.strictSelectedInput{7},'feedback-loss') && ...
    strcmp(broken.reportedSelectedInput{7},'reset-request'), ...
    'Both policies must receive the same simultaneous fault/reset inputs.');
assert(strictConflict.strictRequestedStateId(7) == 5 && ...
    strictConflict.reportedRequestedStateId(7) == 5 && ...
    strictConflict.transitionTableAllowed(7) && ...
    strictConflict.reportedTransitionTableAllowed(7) && ...
    strictConflict.strictGuardPass(7) && ...
    strictConflict.reportedGuardPass(7) && ...
    strictConflict.strictTransitionPass(7) && ...
    strictConflict.reportedTransitionPass(7) && ...
    strictConflict.policyStepAccepted(7) && ...
    ~strictConflict.guardBypassed(7) && ...
    ~strictConflict.priorityViolation(7) && ...
    strictConflict.strictStateMachineAccepted, ...
    'Guarded priority must select the feedback-loss transition to FAULT.');
assert(broken.strictRequestedStateId(7) == 5 && ...
    broken.reportedRequestedStateId(7) == 3 && ...
    broken.observedStateId(7) == 3 && ...
    broken.transitionTableAllowed(7) && ...
    ~broken.reportedTransitionTableAllowed(7) && ...
    broken.strictGuardPass(7) && ~broken.reportedGuardPass(7) && ...
    ~broken.strictPostconditionPass(7) && ...
    broken.reportedPostconditionPass(7) && ...
    ~broken.strictTransitionPass(7) && ...
    ~broken.reportedTransitionPass(7) && ...
    broken.policyStepAccepted(7) && broken.guardBypassed(7) && ...
    broken.priorityViolation(7) && broken.recoveryEvidenceCount == 0 && ...
    ~broken.strictStateMachineAccepted && ...
    broken.reportedStateMachineAccepted && broken.falseApproval && ...
    ~broken.assessmentDecisionCorrect && ...
    strcmp(broken.terminalStatus,'completed-false-approval') && ...
    strcmp(broken.failureMode,'fault-priority-bypassed') && ...
    strcmp(broken.reportingFailureMode, ...
    'last-request-wins-false-approval'), ...
    'Last-request-wins must expose its illegal reset false approval.');
assert(strictConflictWithoutSafeOff.firstViolationStep == 13 && ...
    strictConflictWithoutSafeOff.priorityViolationCount == 0 && ...
    strcmp(strictConflictWithoutSafeOff.failureMode, ...
    'p09-safe-off-proof-unavailable') && ...
    brokenWithoutSafeOff.firstViolationStep == 7 && ...
    brokenWithoutSafeOff.priorityViolationCount == 1 && ...
    brokenWithoutSafeOff.transitionViolationCount == 2 && ...
    ~brokenWithoutSafeOff.falseApproval && ...
    strcmp(brokenWithoutSafeOff.terminalStatus, ...
    'rejected-transition') && ...
    strcmp(brokenWithoutSafeOff.failureMode, ...
    'fault-priority-bypassed') && ...
    strcmp(brokenWithoutSafeOff.reportingFailureMode,'none'), ...
    'A later safe-off rejection must not mask the first priority bypass.');

compatible = model(int8(2),uint8(2),uint8(1),logical(1), ...
    string(' NOMINAL '),string(' NONE '),string(' GUARDED-PRIORITY '));
assert(isequaln(compatible,baseline), ...
    'Compatible integer, Boolean, and scalar-text inputs must normalize.');

expectErrorId(@() model(0,2,true,true,'nominal','none', ...
    'guarded-priority'),'P10:InvalidReadinessConfirmations');
expectAnyError(@() model(5,2,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(1.5,2,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(NaN,2,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(Inf,2,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(1+1i,2,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model([1 2],2,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model('2',2,true,true,'nominal','none','guarded-priority'));
expectErrorId(@() model(2,0,true,true,'nominal','none', ...
    'guarded-priority'),'P10:InvalidRecoveryConfirmations');
expectAnyError(@() model(2,5,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(2,2.5,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(2,NaN,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(2,Inf,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(2,1+1i,true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(2,[1 2],true,true,'nominal','none','guarded-priority'));
expectAnyError(@() model(2,'2',true,true,'nominal','none','guarded-priority'));
expectErrorId(@() model(2,2,2,true,'nominal','none', ...
    'guarded-priority'),'P10:InvalidP09StartupProof');
expectAnyError(@() model(2,2,[true false],true, ...
    'nominal','none','guarded-priority'));
expectAnyError(@() model(2,2,'true',true, ...
    'nominal','none','guarded-priority'));
expectErrorId(@() model(2,2,true,2,'nominal','none', ...
    'guarded-priority'),'P10:InvalidP09SafeOffProof');
expectAnyError(@() model(2,2,true,[true false], ...
    'nominal','none','guarded-priority'));
expectAnyError(@() model(2,2,true,'true', ...
    'nominal','none','guarded-priority'));
expectErrorId(@() model(2,2,true,true,'unsupported','none', ...
    'guarded-priority'),'P10:InvalidScenarioMode');
expectAnyError(@() model(2,2,true,true, ...
    ["nominal" "premature-activation"],'none','guarded-priority'));
expectErrorId(@() model(2,2,true,true,'nominal','unsupported', ...
    'guarded-priority'),'P10:InvalidEventMode');
expectAnyError(@() model(2,2,true,true,'nominal', ...
    ["none" "timeout"],'guarded-priority'));
expectErrorId(@() model(2,2,true,true,'nominal','none', ...
    'unsupported'),'P10:InvalidArbitrationMode');
expectAnyError(@() model(2,2,true,true,'nominal','none', ...
    ["guarded-priority" "last-request-wins"]));

afterMalformed = model();
afterCancellation = model(2,2,true,true, ...
    'nominal','cancellation','guarded-priority');
afterCancellation = model();
afterTimeout = model(2,2,true,true, ...
    'nominal','timeout','guarded-priority');
afterTimeout = model();
afterIncompleteRollback = model(2,2,true,false, ...
    'nominal','cancellation','guarded-priority');
afterIncompleteRollback = model();
afterBroken = model(2,2,true,true, ...
    'fault-reset-conflict','none','last-request-wins');
afterBroken = model();
assert(isequaln(afterMalformed,baseline) && ...
    isequaln(afterCancellation,baseline) && ...
    isequaln(afterTimeout,baseline) && ...
    isequaln(afterIncompleteRollback,baseline) && ...
    isequaln(afterBroken,baseline), ...
    'Every fresh call must recover the exact stateless baseline.');

fprintf('P10 checks passed.\n');
end

function assertStateMachineInvariant(out)
assert(out.transitionCount == 13 && out.stateCount == 6 && ...
    out.rollbackTransitionCount == 3 && ...
    out.eventCheckpointTransition == 6, ...
    'The fixed P10 resource envelope changed.');
assert(isequal(size(out.transitionInputMatrix),[13 9]) && ...
    isequal(size(out.stateOccupancyTrace),[13 6]) && ...
    isequal(size(out.rollbackStateTrace),[3 6]) && ...
    numel(out.transitionEvaluated) == 13 && ...
    numel(out.rollbackTransitionExecuted) == 3, ...
    'A fixed trace or input shape changed.');
assert(out.minimumReadinessConfirmations == 1 && ...
    out.maximumReadinessConfirmations == 4 && ...
    out.minimumRecoveryConfirmations == 1 && ...
    out.maximumRecoveryConfirmations == 4 && ...
    out.maximumSimultaneousTransitionInputs == 2 && ...
    all(out.transitionInputCount >= 1) && ...
    all(out.transitionInputCount <= ...
    out.maximumSimultaneousTransitionInputs) && ...
    isequal(out.transitionInputCount, ...
    sum(out.transitionInputMatrix,2)') && ...
    isequal(out.transitionInputConflict,out.transitionInputCount > 1), ...
    'Control limits or simultaneous-input accounting changed.');

evaluated = out.transitionEvaluated;
notEvaluated = ~evaluated;
numericTraces = {out.sourceStateId,out.strictRequestedStateId, ...
    out.reportedRequestedStateId,out.observedStateId,out.stateIdTrace, ...
    out.readinessEvidenceCountTrace,out.recoveryEvidenceCountTrace};
for k = 1:numel(numericTraces)
    assert(all(isfinite(numericTraces{k}(evaluated))) && ...
        all(isnan(numericTraces{k}(notEvaluated))), ...
        'Evaluated and unavailable numeric transition facts mixed.');
end
assert(all(all(isfinite(out.stateOccupancyTrace(evaluated,:)))) && ...
    all(all(isnan(out.stateOccupancyTrace(notEvaluated,:)))), ...
    'State occupancy must use finite one-hot rows or unavailable rows.');
if any(evaluated)
    occupancy = out.stateOccupancyTrace(evaluated,:);
    assert(all(sum(occupancy,2) == 1) && ...
        all(occupancy(:) == 0 | occupancy(:) == 1), ...
        'Every evaluated state observation must be one-hot.');
end
booleanTraces = {out.transitionTableAllowed, ...
    out.reportedTransitionTableAllowed,out.strictGuardPass, ...
    out.reportedGuardPass,out.strictPostconditionPass, ...
    out.reportedPostconditionPass,out.strictTransitionPass, ...
    out.reportedTransitionPass,out.policyStepAccepted, ...
    out.transitionHazard,out.priorityViolation,out.guardBypassed};
for k = 1:numel(booleanTraces)
    assert(~any(booleanTraces{k}(notEvaluated)), ...
        'Unavailable transition rows must not fabricate Boolean evidence.');
end
for k = find(evaluated)
    assert(out.transitionTableAllowed(k) == ...
        out.transitionTable(out.sourceStateId(k), ...
        out.strictRequestedStateId(k)) && ...
        out.reportedTransitionTableAllowed(k) == ...
        out.transitionTable(out.sourceStateId(k), ...
        out.reportedRequestedStateId(k)) && ...
        out.strictPostconditionPass(k) == ...
        (out.observedStateId(k) == out.strictRequestedStateId(k)) && ...
        out.reportedPostconditionPass(k) == ...
        (out.observedStateId(k) == out.reportedRequestedStateId(k)) && ...
        out.stateIdTrace(k) == out.observedStateId(k), ...
        'A transition fact is inconsistent with its source or destination.');
end
assert(isequal(out.strictTransitionPass, ...
    out.transitionTableAllowed & out.strictGuardPass & ...
    out.strictPostconditionPass) && ...
    isequal(out.reportedTransitionPass, ...
    out.reportedTransitionTableAllowed & out.reportedGuardPass & ...
    out.reportedPostconditionPass) && ...
    isequal(out.transitionHazard,evaluated & ~out.strictTransitionPass), ...
    'Transition pass and hazard facts must preserve their formulas.');
assert(out.transitionViolationCount == ...
    sum(evaluated & ~out.strictTransitionPass) && ...
    out.reportedViolationCount == ...
    sum(evaluated & ~out.reportedTransitionPass) && ...
    out.policyViolationCount == ...
    sum(evaluated & ~out.policyStepAccepted) && ...
    out.priorityViolationCount == ...
    sum(evaluated & out.priorityViolation) && ...
    sum(out.stateObservationCount) == sum(evaluated), ...
    'Nominal counters must derive from fixed transition facts.');
assert(out.sequenceCompleted == all(evaluated) && ...
    out.strictStateMachineAccepted == ...
    (out.sequenceCompleted && all(out.strictTransitionPass) && ...
    out.sequenceFinalStateId == 1) && ...
    out.reportedStateMachineAccepted == ...
    (out.sequenceCompleted && all(out.policyStepAccepted) && ...
    out.sequenceFinalStateId == 1) && ...
    out.falseApproval == ...
    (out.sequenceCompleted && out.reportedStateMachineAccepted && ...
    ~out.strictStateMachineAccepted), ...
    'Acceptance must derive from complete transition facts.');

executed = out.rollbackTransitionExecuted;
if out.eventObserved
    assert(out.rollbackPerformed && all(executed) && ...
        all(all(isfinite(out.rollbackStateTrace))), ...
        'Observed interruptions must execute the bounded rollback.');
    for k = find(executed)
        assert(out.rollbackTransitionTableAllowed(k) == ...
            out.transitionTable(out.rollbackSourceStateId(k), ...
            out.rollbackRequestedStateId(k)) && ...
            out.rollbackPostconditionPass(k) == ...
            (out.rollbackObservedStateId(k) == ...
            out.rollbackRequestedStateId(k)), ...
            'A rollback fact is inconsistent with its source or destination.');
    end
else
    assert(~out.rollbackPerformed && ~any(executed) && ...
        all(isnan(out.rollbackSourceStateId)) && ...
        all(isnan(out.rollbackRequestedStateId)) && ...
        all(isnan(out.rollbackObservedStateId)) && ...
        all(all(isnan(out.rollbackStateTrace))) && ...
        isnan(out.rollbackFinalStateId), ...
        'No-event cases must not fabricate rollback evidence.');
end
assert(isequal(out.rollbackTransitionPass, ...
    out.rollbackTransitionTableAllowed & out.rollbackGuardPass & ...
    out.rollbackPostconditionPass) && ...
    isequal(out.rollbackHazard,executed & ~out.rollbackTransitionPass) && ...
    out.rollbackViolationCount == ...
    sum(executed & ~out.rollbackTransitionPass) && ...
    out.totalViolationCount == ...
    out.transitionViolationCount + out.rollbackViolationCount, ...
    'Rollback pass, hazard, and aggregate counters must remain factual.');
end

function expectErrorId(operation,expectedId)
try
    operation();
catch caught
    assert(strcmp(caught.identifier,expectedId), ...
        'Malformed input raised the wrong diagnostic identifier.');
    return;
end
error('P10:MissingExpectedError','Malformed input was accepted.');
end

function expectAnyError(operation)
try
    operation();
catch
    return;
end
error('P10:MissingExpectedError','Malformed input was accepted.');
end
