function run_checks
%RUN_CHECKS Independent P05 allocation, resource, and containment checks.
baseline = model('software','hardware',30,40,'available','none','complete');
repeat = model('software','hardware',30,40,'available','none','complete');
assert(isequaln(baseline,repeat), ...
    'Repeated baseline calls must be deterministic and stateless.');
assert(baseline.functionCount == 10 && baseline.domainCount == 2 && ...
    isequal(size(baseline.ownerMatrix),[10 2]) && ...
    isequal(size(baseline.softwareCostUnitsPerUpdate),[10 1]) && ...
    isequal(size(baseline.hardwareCostAllocationUnits),[10 1]), ...
    'The fixed ten-function, two-domain resource envelope changed.');
assert(all(baseline.ownerCountPerFunction == 1) && ...
    sum(baseline.ownerMatrix(:)) == 10, ...
    'Every P04 function must retain exactly one execution-domain owner.');
expectedFunctionNames = { ...
    'Capture intent', ...
    'Validate authority', ...
    'Observe position', ...
    'Compute error', ...
    'Generate correction', ...
    'Update physical state', ...
    'Confirm requested behavior', ...
    'Handle cancellation', ...
    'Enforce deadline', ...
    'Report outcome'};
expectedFunctionInputs = { ...
    'request and cancellation', ...
    'requested angle and authority', ...
    'physical position', ...
    'accepted target and observation', ...
    'signed error and response fraction', ...
    'bounded correction', ...
    'request error, tolerance, and evidence depth', ...
    'cancellation and transaction state', ...
    'elapsed time and deadline', ...
    'terminal state and evidence'};
expectedFunctionOutputs = { ...
    'preserved requested angle', ...
    'accepted or rejected request', ...
    'observed position in deg', ...
    'signed error in deg', ...
    'correction in deg per update', ...
    'new physical position in deg', ...
    'completion-proxy decision', ...
    'cancelled terminal state and safe-hold requirement', ...
    'deadline-missed terminal state and safe-hold requirement', ...
    'operator-visible result'};
expectedFunctionFailureModes = { ...
    'intent lost', ...
    'out-of-authority request passes downstream', ...
    'state is unobservable', ...
    'wrong target or sign', ...
    'unstable or ineffective correction', ...
    'requested change not produced', ...
    'premature or missing confirmation', ...
    'cancellation ignored', ...
    'late result accepted', ...
    'local success misreported as system success'};
assert(isequal(baseline.functionNames,expectedFunctionNames) && ...
    isequal(baseline.functionInputs,expectedFunctionInputs) && ...
    isequal(baseline.functionOutputs,expectedFunctionOutputs) && ...
    isequal(baseline.functionFailureModes,expectedFunctionFailureModes), ...
    'P05 must preserve every P04 function contract and failure observable.');
assert(all(strcmp(baseline.functionOwner(baseline.fixedSoftwareIndices), ...
    'software')) && ...
    all(strcmp(baseline.functionOwner(baseline.fixedHardwareIndices), ...
    'hardware')) && baseline.bindingValid, ...
    'Fixed software boundaries and physical hardware endpoints must remain bound.');

expectedSoftwareCosts = [2; 2; 0; 6; 8; 0; 4; 2; 2; 2];
expectedHardwareCosts = [0; 3; 5; 7; 9; 8; 0; 3; 3; 0];
assert(isequal(baseline.softwareCostUnitsPerUpdate,expectedSoftwareCosts) && ...
    isequal(baseline.hardwareCostAllocationUnits,expectedHardwareCosts), ...
    'The transparent P05 cost vectors changed unexpectedly.');
expectedSoftwareDemand = 2 + 6 + 8 + 4 + 2;
expectedHardwareDemand = 3 + 5 + 8 + 3 + 3;
assert(expectedSoftwareDemand == 22 && expectedHardwareDemand == 22 && ...
    baseline.softwareDemandUnitsPerUpdate == expectedSoftwareDemand && ...
    baseline.hardwareDemandAllocationUnits == expectedHardwareDemand, ...
    'Baseline demand must equal the independent visible-cost sums.');
assert(baseline.softwareMarginUnitsPerUpdate == 8 && ...
    baseline.hardwareMarginAllocationUnits == 18 && ...
    abs(baseline.softwareUtilizationPercent - 100*22/30) < 1e-12 && ...
    baseline.hardwareUtilizationPercent == 55, ...
    'Baseline margins and utilization must follow demand/capacity directly.');
assert(baseline.nominalResourceFit && baseline.bindingValid && ...
    baseline.softwareFaultIndependentSupervision && ...
    baseline.allRequiredFunctionsAvailable && ...
    baseline.allocationContractMet && baseline.reportedFeasible && ...
    ~baseline.falseFeasible && strcmp(baseline.failureMode,'none'), ...
    'The valid baseline must pass the complete allocation contract.');

hardwareControl = model('hardware','hardware',30,40, ...
    'available','none','complete');
softwareSupervision = model('software','software',30,40, ...
    'available','none','complete');
hardwareControlSoftwareSupervision = model('hardware','software',30,40, ...
    'available','none','complete');
assert(hardwareControl.softwareDemandUnitsPerUpdate == 8 && ...
    hardwareControl.hardwareDemandAllocationUnits == 38, ...
    'Hardware-owned control must transfer exactly 14 SW and 16 HW units.');
assert(softwareSupervision.softwareDemandUnitsPerUpdate == 28 && ...
    softwareSupervision.hardwareDemandAllocationUnits == 13, ...
    'Software-owned supervision must transfer its declared three-function costs.');
assert(hardwareControlSoftwareSupervision.softwareDemandUnitsPerUpdate == 14 && ...
    hardwareControlSoftwareSupervision.hardwareDemandAllocationUnits == 29, ...
    'The fourth owner combination must preserve independent cost sums.');
assert(all(strcmp(hardwareControl.functionOwner([4 5]),'hardware')) && ...
    all(strcmp(hardwareControl.functionOwner([2 8 9]),'hardware')) && ...
    all(strcmp(softwareSupervision.functionOwner([4 5]),'software')) && ...
    all(strcmp(softwareSupervision.functionOwner([2 8 9]),'software')), ...
    'Control and supervision levers must affect only their declared functions.');
assert(isequal(baseline.functionOwner([1 2 3 6 7 8 9 10]), ...
    hardwareControl.functionOwner([1 2 3 6 7 8 9 10])) && ...
    isequal(baseline.functionOwner([1 3 4 5 6 7 10]), ...
    softwareSupervision.functionOwner([1 3 4 5 6 7 10])), ...
    'Each owner lever must leave every other owner unchanged.');
assert(~softwareSupervision.softwareFaultIndependentSupervision && ...
    ~softwareSupervision.allocationContractMet && ...
    strcmp(softwareSupervision.failureMode,'common-mode-supervision'), ...
    'Nominally available software supervision must still fail the declared independence requirement.');

exactCapacity = model('software','hardware',22,22, ...
    'available','none','complete');
assert(exactCapacity.nominalResourceFit && exactCapacity.allocationContractMet && ...
    exactCapacity.softwareMarginUnitsPerUpdate == 0 && ...
    exactCapacity.hardwareMarginAllocationUnits == 0 && ...
    exactCapacity.softwareUtilizationPercent == 100 && ...
    exactCapacity.hardwareUtilizationPercent == 100, ...
    'Demand exactly equal to declared capacity must pass inclusively.');
softwareBelow = model('software','hardware',21.999,22, ...
    'available','none','complete');
hardwareBelow = model('software','hardware',22,21.999, ...
    'available','none','complete');
dualBelow = model('software','hardware',21.999,21.999, ...
    'available','none','complete');
assert(~softwareBelow.softwareResourceFit && hardwareBelow.softwareResourceFit && ...
    strcmp(softwareBelow.failureMode,'software-capacity-exceeded'), ...
    'Capacity just below software demand must fail only that domain.');
assert(~hardwareBelow.hardwareResourceFit && softwareBelow.hardwareResourceFit && ...
    strcmp(hardwareBelow.failureMode,'hardware-capacity-exceeded'), ...
    'Capacity just below hardware demand must fail only that domain.');
assert(~dualBelow.nominalResourceFit && ...
    strcmp(dualBelow.failureMode,'dual-capacity-exceeded'), ...
    'Both capacities below demand must report a dual overflow.');
zeroCapacities = model('software','hardware',0,0, ...
    'available','none','complete');
assert(~zeroCapacities.nominalResourceFit && ...
    ~zeroCapacities.softwareExecutionAvailable && ...
    ~zeroCapacities.hardwareExecutionAvailable && ...
    ~any(zeroCapacities.functionAvailable) && ...
    isinf(zeroCapacities.softwareUtilizationPercent) && ...
    isinf(zeroCapacities.hardwareUtilizationPercent), ...
    'Positive fixed demand against zero capacity must be visibly unbounded.');
maxBounded = model('hardware','hardware',1000,1000, ...
    'available','none','complete');
assert(maxBounded.functionCount == 10 && maxBounded.domainCount == 2 && ...
    maxBounded.nominalResourceFit && maxBounded.maxCapacityUnits == 1000, ...
    'Maximum allowed capacities must retain fixed resources and valid sums.');

hardwareCancel = model('software','hardware',30,40, ...
    'stalled','cancellation','complete');
hardwareDeadline = model('software','hardware',30,40, ...
    'stalled','deadline','complete');
assert(~hardwareCancel.allRequiredFunctionsAvailable && ...
    ~hardwareCancel.softwareExecutionAvailable && ...
    hardwareCancel.hardwareExecutionAvailable && ...
    hardwareCancel.eventFunctionIndex == 8 && ...
    strcmp(hardwareCancel.eventGuardName,'Handle cancellation') && ...
    hardwareCancel.eventGuardAvailable && hardwareCancel.eventHandled && ...
    hardwareCancel.safeHoldRequestAvailable && ...
    hardwareCancel.allocationContractMet && ...
    strcmp(hardwareCancel.scenarioStatus,'cancellation-contained'), ...
    'Hardware supervision must retain the cancellation boundary during a SW stall.');
assert(~hardwareDeadline.allRequiredFunctionsAvailable && ...
    hardwareDeadline.eventFunctionIndex == 9 && ...
    strcmp(hardwareDeadline.eventGuardName,'Enforce deadline') && ...
    hardwareDeadline.eventGuardAvailable && hardwareDeadline.eventHandled && ...
    hardwareDeadline.safeHoldRequestAvailable && ...
    hardwareDeadline.allocationContractMet && ...
    strcmp(hardwareDeadline.scenarioStatus,'deadline-contained'), ...
    'Hardware supervision must retain the deadline/timeout boundary during a SW stall.');
assert(any(strcmp(hardwareCancel.lostFunctionNames,'Capture intent')) && ...
    any(strcmp(hardwareCancel.lostFunctionNames,'Report outcome')), ...
    'Containment must not masquerade as availability of the full transaction.');
resourceStarvedGuard = model('software','hardware',30,21.999, ...
    'stalled','cancellation','complete');
assert(~resourceStarvedGuard.hardwareResourceFit && ...
    ~resourceStarvedGuard.hardwareExecutionAvailable && ...
    ~resourceStarvedGuard.eventGuardAvailable && ...
    ~resourceStarvedGuard.eventHandled && ...
    ~resourceStarvedGuard.safeHoldRequestAvailable && ...
    ~resourceStarvedGuard.allocationContractMet && ...
    strcmp(resourceStarvedGuard.scenarioStatus,'resource-overload') && ...
    strcmp(resourceStarvedGuard.failureMode,'hardware-capacity-exceeded'), ...
    'An overloaded owner domain cannot supply its event guard or safe-hold request.');

softwareCancel = model('software','software',30,40, ...
    'stalled','cancellation','complete');
softwareDeadline = model('software','software',30,40, ...
    'stalled','deadline','complete');
assert(softwareCancel.nominalResourceFit && ...
    ~softwareCancel.softwareFaultIndependentSupervision && ...
    ~softwareCancel.eventGuardAvailable && ~softwareCancel.eventHandled && ...
    ~softwareCancel.safeHoldRequestAvailable && ...
    ~softwareCancel.allocationContractMet && ...
    strcmp(softwareCancel.failureMode,'cancellation-unhandled') && ...
    strcmp(softwareCancel.scenarioStatus,'cancellation-unhandled'), ...
    'Software-owned cancellation must expose common-mode guard loss.');
assert(softwareDeadline.nominalResourceFit && ...
    ~softwareDeadline.eventGuardAvailable && ~softwareDeadline.eventHandled && ...
    ~softwareDeadline.safeHoldRequestAvailable && ...
    strcmp(softwareDeadline.failureMode,'deadline-unhandled') && ...
    strcmp(softwareDeadline.scenarioStatus,'deadline-unhandled'), ...
    'Software-owned deadline/timeout supervision must expose common-mode guard loss.');
stalledWithoutEvent = model('software','hardware',30,40, ...
    'stalled','none','complete');
assert(~stalledWithoutEvent.allRequiredFunctionsAvailable && ...
    ~stalledWithoutEvent.scenarioRequirementMet && ...
    ~stalledWithoutEvent.allocationContractMet && ...
    strcmp(stalledWithoutEvent.failureMode,'required-functions-unavailable') && ...
    strcmp(stalledWithoutEvent.scenarioStatus,'software-common-mode-loss'), ...
    'A no-event stalled scenario must not be called transaction-ready.');

brokenResourceOnly = model('software','software',30,40, ...
    'stalled','cancellation','resource-only');
assert(brokenResourceOnly.resourceOnlyDecision && ...
    brokenResourceOnly.reportedFeasible && brokenResourceOnly.falseFeasible && ...
    ~brokenResourceOnly.allocationContractMet && ...
    ~brokenResourceOnly.eventHandled && ...
    strcmp(brokenResourceOnly.decisionStatus,'approved'), ...
    'Resource-only evidence must expose the deliberately false approval.');
assert(isequal(brokenResourceOnly.functionOwner,softwareCancel.functionOwner) && ...
    isequal(brokenResourceOnly.softwareContributionUnits, ...
    softwareCancel.softwareContributionUnits) && ...
    isequal(brokenResourceOnly.hardwareContributionUnits, ...
    softwareCancel.hardwareContributionUnits) && ...
    isequal(brokenResourceOnly.functionAvailable,softwareCancel.functionAvailable), ...
    'Assessment mode may change the report but never the underlying allocation facts.');
stateProbe = model('software','hardware',30,40, ...
    'stalled','deadline','resource-only');
assert(isequal(stateProbe.functionOwner,baseline.functionOwner) && ...
    isequal(stateProbe.softwareCostUnitsPerUpdate, ...
    baseline.softwareCostUnitsPerUpdate) && ...
    isequal(stateProbe.hardwareCostAllocationUnits, ...
    baseline.hardwareCostAllocationUnits) && ...
    stateProbe.softwareDemandUnitsPerUpdate == ...
    baseline.softwareDemandUnitsPerUpdate && ...
    stateProbe.hardwareDemandAllocationUnits == ...
    baseline.hardwareDemandAllocationUnits, ...
    'State, event, and assessment inputs must not mutate ownership or nominal costs.');

compatible = model(string('software'),string('hardware'),uint8(30), ...
    single(40),string('available'),string('none'),string('complete'));
assert(isequaln(compatible,baseline), ...
    'Compatible numeric scalar and scalar-text classes must normalize identically.');

expectErrorId(@() model('processor','hardware',30,40, ...
    'available','none','complete'),'P05:InvalidControlOwner');
expectErrorId(@() model('software','fpga',30,40, ...
    'available','none','complete'),'P05:InvalidSupervisionOwner');
expectErrorId(@() model('software','hardware',30,40, ...
    'failed','none','complete'),'P05:InvalidSoftwareState');
expectErrorId(@() model('software','hardware',30,40, ...
    'available','reset','complete'),'P05:InvalidEventMode');
expectErrorId(@() model('software','hardware',30,40, ...
    'available','none','optimistic'),'P05:InvalidAssessmentMode');
expectErrorId(@() model(string({'software','hardware'}),'hardware',30,40, ...
    'available','none','complete'),'P05:InvalidControlOwner');
expectAnyError(@() model(1,'hardware',30,40,'available','none','complete'));
expectErrorId(@() model('software','hardware',NaN,40, ...
    'available','none','complete'),'P05:InvalidCapacity');
expectAnyError(@() model('software','hardware',Inf,40, ...
    'available','none','complete'));
expectAnyError(@() model('software','hardware',1+1i,40, ...
    'available','none','complete'));
expectAnyError(@() model('software','hardware',[30 31],40, ...
    'available','none','complete'));
expectErrorId(@() model('software','hardware',-1,40, ...
    'available','none','complete'),'P05:InvalidCapacity');
expectAnyError(@() model('software','hardware',30,NaN, ...
    'available','none','complete'));
expectAnyError(@() model('software','hardware',30,Inf, ...
    'available','none','complete'));
expectAnyError(@() model('software','hardware',30,1+1i, ...
    'available','none','complete'));
expectAnyError(@() model('software','hardware',30,[40 41], ...
    'available','none','complete'));
expectAnyError(@() model('software','hardware',30,-1, ...
    'available','none','complete'));
expectErrorId(@() model('software','hardware',1000.1,40, ...
    'available','none','complete'),'P05:ResourceBound');
expectErrorId(@() model('software','hardware',30,1000.1, ...
    'available','none','complete'),'P05:ResourceBound');

afterFailure = model('software','hardware',30,40,'available','none','complete');
assert(isequaln(afterFailure,baseline), ...
    'A valid call after malformed inputs must recover without hidden state.');
afterIsolationProbe = model('software','hardware',30,40, ...
    'available','none','complete');
assert(isequaln(afterIsolationProbe,baseline), ...
    'Calls must remain isolated from overload, stalled, and broken paths.');
disp('P05 checks passed: allocation, resources, events, limits, recovery, and isolation.');
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
