function run_checks
%RUN_CHECKS Independent P06 command reachability and value-lineage checks.
baseline = model(30,0,45,0.35,'none','none','endpoint-receipt');
repeat = model(30,0,45,0.35,'none','none','endpoint-receipt');
defaults = model();
assert(isequaln(baseline,repeat) && isequaln(defaults,baseline), ...
    'Repeated and default baseline calls must be deterministic and stateless.');
assertTraceInvariant(baseline);

expectedStageNames = { ...
    'Capture intent', ...
    'Validate authority', ...
    'Compute error', ...
    'Generate correction', ...
    'Update physical state input latch'};
expectedStageOwners = { ...
    'application-software', ...
    'independent-hardware', ...
    'application-software', ...
    'application-software', ...
    'hardware-interface'};
expectedStageUnits = {'deg','deg','deg','deg/update','deg/update'};
expectedBoundaryNames = { ...
    'request-to-authority', ...
    'authority-to-error', ...
    'error-to-correction', ...
    'correction-to-actuator'};
assert(isequal(baseline.stageNames,expectedStageNames) && ...
    isequal(baseline.stageOwners,expectedStageOwners) && ...
    isequal(baseline.stageUnits,expectedStageUnits) && ...
    isequal(baseline.boundaryNames,expectedBoundaryNames), ...
    'P06 must preserve the declared P04/P05 stage, owner, unit, and boundary map.');
assert(baseline.stageCount == 5 && baseline.boundaryCount == 4 && ...
    baseline.maxAbsAngleDeg == 180 && ...
    isequal(size(baseline.stageReached),[1 5]) && ...
    isequal(size(baseline.stageOutputValue),[1 5]) && ...
    isequal(size(baseline.boundaryCrossed),[1 4]), ...
    'The fixed five-stage, four-boundary resource envelope changed.');
assert(all(baseline.stageReached) && all(baseline.boundaryAttempted) && ...
    all(baseline.boundaryCrossed) && ~any(baseline.boundaryOpen) && ...
    baseline.deepestReachedStage == 5 && ...
    baseline.crossedBoundaryCount == 4, ...
    'The baseline command must cross all four handoffs.');
assert(isequal(baseline.stageOutputValue,[30 30 30 10.5 10.5]) && ...
    baseline.acceptedTargetDeg == 30 && baseline.errorDeg == 30 && ...
    baseline.correctionDegPerUpdate == 10.5 && ...
    baseline.authorityMarginDeg == 15, ...
    'Baseline values must follow the independent target, error, and correction equations.');
assert(baseline.authorityValid && baseline.localDispatchObserved && ...
    baseline.actuatorCommandReceived && baseline.payloadPreservedToEndpoint && ...
    baseline.terminalOutcomeHandled && baseline.traceContractMet && ...
    baseline.reportedSuccess && ~baseline.falseSuccess && ...
    strcmp(baseline.terminalStatus,'delivered') && ...
    strcmp(baseline.failureMode,'none'), ...
    'The valid baseline must report exact logical endpoint delivery.');
assert(~baseline.eventObserved && ~baseline.safeHoldRequired && ...
    ~baseline.safeHoldRequestAvailable, ...
    'The nominal path must not invent a terminal event or safe response.');

authorityBelow = model(30,0,29.999,0.35, ...
    'none','none','endpoint-receipt');
authorityExact = model(30,0,30,0.35, ...
    'none','none','endpoint-receipt');
authorityWide = model(30,0,90,0.35, ...
    'none','none','endpoint-receipt');
negativeExact = model(-30,0,30,0.35, ...
    'none','none','endpoint-receipt');
for candidate = {authorityBelow,authorityExact,authorityWide,negativeExact}
    assertTraceInvariant(candidate{1});
end
assert(authorityBelow.deepestReachedStage == 2 && ...
    isequal(authorityBelow.stageReached,[true true false false false]) && ...
    ~authorityBelow.boundaryAttempted(2) && ...
    ~authorityBelow.actuatorCommandReceived && ...
    authorityBelow.safeHoldRequired && ...
    authorityBelow.safeHoldRequestAvailable && ...
    authorityBelow.terminalOutcomeHandled && authorityBelow.traceContractMet && ...
    strcmp(authorityBelow.terminalStatus,'authority-rejected') && ...
    strcmp(authorityBelow.failureMode,'request-rejected'), ...
    'A just-outside request must stop at authority with a logical safe response.');
assert(authorityExact.authorityValid && authorityExact.authorityMarginDeg == 0 && ...
    authorityExact.actuatorCommandReceived && authorityWide.actuatorCommandReceived, ...
    'Authority equality must pass inclusively and wider authority must preserve delivery.');
assert(negativeExact.authorityValid && negativeExact.errorDeg == -30 && ...
    negativeExact.correctionDegPerUpdate == -10.5 && ...
    negativeExact.stageOutputValue(5) == -10.5, ...
    'Negative commands must preserve sign through the symmetric authority path.');

zeroError = model(30,30,45,0.35, ...
    'none','none','endpoint-receipt');
zeroResponse = model(30,0,45,0, ...
    'none','none','endpoint-receipt');
fullResponse = model(30,0,45,1, ...
    'none','none','endpoint-receipt');
maxEnvelope = model(180,-180,180,1, ...
    'none','none','endpoint-receipt');
for candidate = {zeroError,zeroResponse,fullResponse,maxEnvelope}
    assertTraceInvariant(candidate{1});
end
assert(zeroError.errorDeg == 0 && zeroError.correctionDegPerUpdate == 0 && ...
    zeroError.actuatorCommandReceived, ...
    'Zero error must deliver a zero correction without inventing a path failure.');
assert(zeroResponse.errorDeg == 30 && zeroResponse.correctionDegPerUpdate == 0 && ...
    zeroResponse.actuatorCommandReceived, ...
    'Zero response fraction must be a valid limiting calculation.');
assert(fullResponse.correctionDegPerUpdate == 30 && ...
    maxEnvelope.errorDeg == 360 && maxEnvelope.correctionDegPerUpdate == 360 && ...
    maxEnvelope.payloadPreservedToEndpoint, ...
    'Full response and maximum bounded inputs must retain transparent arithmetic.');

boundaryChoices = { ...
    'request-to-authority', ...
    'authority-to-error', ...
    'error-to-correction', ...
    'correction-to-actuator'};
for k = 1:numel(boundaryChoices)
    stopped = model(30,0,45,0.35,boundaryChoices{k}, ...
        'none','endpoint-receipt');
    assertTraceInvariant(stopped);
    assert(stopped.firstOpenBoundary == k && ...
        stopped.deepestReachedStage == k && ...
        stopped.boundaryAttempted(k) && ~stopped.boundaryCrossed(k) && ...
        stopped.crossedBoundaryCount == k - 1 && ...
        ~stopped.actuatorCommandReceived && ~stopped.traceContractMet && ...
        strcmp(stopped.terminalStatus,'boundary-open') && ...
        strcmp(stopped.failureMode,boundaryChoices{k}), ...
        'Each open boundary must stop the trace at its source stage.');
end

cancelled = model(30,0,45,0.35,'none', ...
    'cancellation','endpoint-receipt');
timedOut = model(30,0,45,0.35,'none', ...
    'timeout','endpoint-receipt');
tied = model(30,0,45,0.35,'none', ...
    'cancellation-timeout-tie','endpoint-receipt');
for candidate = {cancelled,timedOut,tied}
    assertTraceInvariant(candidate{1});
    assert(candidate{1}.eventGuardReached && candidate{1}.eventObserved && ...
        candidate{1}.safeHoldRequired && ...
        candidate{1}.safeHoldRequestAvailable && ...
        candidate{1}.localDispatchObserved && ...
        ~candidate{1}.boundaryCrossed(4) && ...
        ~candidate{1}.actuatorCommandReceived && ...
        candidate{1}.terminalOutcomeHandled && candidate{1}.traceContractMet, ...
        'A reached terminal guard must contain its event before endpoint receipt.');
end
assert(cancelled.cancellationObserved && ~cancelled.timeoutObserved && ...
    strcmp(cancelled.terminalStatus,'cancelled') && ...
    strcmp(cancelled.failureMode,'cancelled'), ...
    'Cancellation must remain distinguishable from timeout.');
assert(~timedOut.cancellationObserved && timedOut.timeoutObserved && ...
    strcmp(timedOut.terminalStatus,'timed-out') && ...
    strcmp(timedOut.failureMode,'timeout-observed'), ...
    'Timeout must be an injected logical guard event, not measured timing.');
assert(tied.cancellationObserved && tied.timeoutObserved && ...
    tied.tieResolvedToCancellation && strcmp(tied.terminalStatus,'cancelled'), ...
    'Cancellation must retain precedence in the injected cancellation/timeout tie.');

unreachedGuard = model(30,0,45,0.35,'error-to-correction', ...
    'cancellation','endpoint-receipt');
validationFirst = model(60,0,45,0.35,'none', ...
    'cancellation','endpoint-receipt');
eventBeforeOpenFinal = model(30,0,45,0.35,'correction-to-actuator', ...
    'timeout','endpoint-receipt');
assertTraceInvariant(unreachedGuard);
assertTraceInvariant(validationFirst);
assertTraceInvariant(eventBeforeOpenFinal);
assert(~unreachedGuard.eventGuardReached && ~unreachedGuard.eventObserved && ...
    ~unreachedGuard.safeHoldRequired && ...
    strcmp(unreachedGuard.terminalStatus,'boundary-open'), ...
    'An event cannot be observed by a guard that the command never reaches.');
assert(~validationFirst.eventGuardReached && ...
    ~validationFirst.cancellationObserved && validationFirst.safeHoldRequired && ...
    strcmp(validationFirst.terminalStatus,'authority-rejected'), ...
    'Inherited authority validation must stop the path before the later event guard.');
assert(eventBeforeOpenFinal.timeoutObserved && ...
    strcmp(eventBeforeOpenFinal.terminalStatus,'timed-out'), ...
    'A reached event guard must determine the terminal before an open final handoff.');

completeBrokenTrace = model(30,0,45,0.35,'correction-to-actuator', ...
    'none','endpoint-receipt');
brokenDispatchOnly = model(30,0,45,0.35,'correction-to-actuator', ...
    'none','dispatch-only');
assertTraceInvariant(completeBrokenTrace);
assertTraceInvariant(brokenDispatchOnly);
assert(isequaln(completeBrokenTrace.stageReached, ...
    brokenDispatchOnly.stageReached) && ...
    isequaln(completeBrokenTrace.stageOutputValue, ...
    brokenDispatchOnly.stageOutputValue) && ...
    isequal(completeBrokenTrace.boundaryAttempted, ...
    brokenDispatchOnly.boundaryAttempted) && ...
    isequal(completeBrokenTrace.boundaryCrossed, ...
    brokenDispatchOnly.boundaryCrossed) && ...
    completeBrokenTrace.localDispatchObserved && ...
    ~completeBrokenTrace.reportedSuccess && ...
    brokenDispatchOnly.reportedSuccess && brokenDispatchOnly.falseSuccess && ...
    ~brokenDispatchOnly.actuatorCommandReceived, ...
    'Dispatch-only assessment may change only the report, never path truth.');
baselineDispatchOnly = model(30,0,45,0.35,'none','none','dispatch-only');
assert(baselineDispatchOnly.reportedSuccess && ...
    baselineDispatchOnly.actuatorCommandReceived && ...
    ~baselineDispatchOnly.falseSuccess, ...
    'Dispatch evidence is not false when endpoint receipt is independently present.');

compatible = model(int16(30),single(0),uint8(45),single(0.5), ...
    string(' NONE '),string('NONE'),string('ENDPOINT-RECEIPT'));
compatibleReference = model(30,0,45,0.5,'none','none','endpoint-receipt');
assert(isequaln(compatible,compatibleReference), ...
    'Compatible scalar numeric and scalar-text classes must normalize identically.');

expectErrorId(@() model(NaN,0,45,0.35,'none','none', ...
    'endpoint-receipt'),'P06:InvalidAngle');
expectAnyError(@() model(Inf,0,45,0.35,'none','none','endpoint-receipt'));
expectAnyError(@() model(1+1i,0,45,0.35,'none','none','endpoint-receipt'));
expectAnyError(@() model([30 31],0,45,0.35,'none','none','endpoint-receipt'));
expectAnyError(@() model('30',0,45,0.35,'none','none','endpoint-receipt'));
expectErrorId(@() model(180.001,0,45,0.35,'none','none', ...
    'endpoint-receipt'),'P06:InvalidAngle');
expectAnyError(@() model(30,-180.001,45,0.35,'none','none', ...
    'endpoint-receipt'));
expectErrorId(@() model(30,0,0,0.35,'none','none', ...
    'endpoint-receipt'),'P06:InvalidAuthority');
expectAnyError(@() model(30,0,-1,0.35,'none','none','endpoint-receipt'));
expectAnyError(@() model(30,0,180.001,0.35,'none','none', ...
    'endpoint-receipt'));
expectErrorId(@() model(30,0,45,NaN,'none','none', ...
    'endpoint-receipt'),'P06:InvalidResponseFraction');
expectAnyError(@() model(30,0,45,-0.001,'none','none','endpoint-receipt'));
expectAnyError(@() model(30,0,45,1.001,'none','none','endpoint-receipt'));
expectAnyError(@() model(30,0,45,[0.3 0.4],'none','none', ...
    'endpoint-receipt'));
expectErrorId(@() model(30,0,45,0.35,'missing-boundary','none', ...
    'endpoint-receipt'),'P06:InvalidBoundary');
expectErrorId(@() model(30,0,45,0.35,'none','deadline', ...
    'endpoint-receipt'),'P06:InvalidEventMode');
expectErrorId(@() model(30,0,45,0.35,'none','none', ...
    'receipt-only'),'P06:InvalidAssessmentMode');
expectAnyError(@() model(30,0,45,0.35, ...
    string({'none','error-to-correction'}),'none','endpoint-receipt'));
expectAnyError(@() model(30,0,45,0.35,1,'none','endpoint-receipt'));

afterMalformed = model(30,0,45,0.35,'none','none','endpoint-receipt');
afterFailures = model(30,0,45,0.35,'none','none','endpoint-receipt');
assert(isequaln(afterMalformed,baseline) && isequaln(afterFailures,baseline), ...
    'A valid call after malformed, guarded, and broken calls must recover exactly.');
disp('P06 checks passed: values, boundaries, guards, limits, recovery, and isolation.');
end

function assertTraceInvariant(out)
assert(out.stageCount == 5 && out.boundaryCount == 4 && ...
    isequal(size(out.stageReached),[1 5]) && ...
    isequal(size(out.stageOutputValue),[1 5]) && ...
    isequal(size(out.boundaryAttempted),[1 4]) && ...
    isequal(size(out.boundaryCrossed),[1 4]) && ...
    isequal(size(out.boundaryOpen),[1 4]), ...
    'Every trace must stay inside the fixed resource envelope.');
assert(out.stageReached(1) && ...
    isequal(out.stageReached(2:end),out.boundaryCrossed) && ...
    all(~out.boundaryCrossed | out.boundaryAttempted) && ...
    all(diff(double(out.stageReached)) <= 0), ...
    'Stage reachability must be a contiguous prefix defined by crossed boundaries.');
assert(all(isfinite(out.stageOutputValue(out.stageReached))) && ...
    all(isnan(out.stageOutputValue(~out.stageReached))), ...
    'Reached stages need finite outputs and unreachable stages need no value.');
assert(out.deepestReachedStage == find(out.stageReached,1,'last') && ...
    out.crossedBoundaryCount == sum(out.boundaryCrossed), ...
    'Trace summary indices must derive from the visible Boolean arrays.');
if out.firstOpenBoundary > 0
    assert(out.boundaryAttempted(out.firstOpenBoundary) && ...
        out.boundaryOpen(out.firstOpenBoundary) && ...
        ~out.boundaryCrossed(out.firstOpenBoundary), ...
        'The first open boundary must be evaluated but not crossed.');
end
if out.actuatorCommandReceived
    assert(out.stageReached(end) && out.payloadPreservedToEndpoint && ...
        out.stageOutputValue(end) == out.correctionDegPerUpdate, ...
        'Endpoint receipt must preserve the generated correction value.');
end
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
