function run_checks()
%RUN_CHECKS Independent limits, failures, rollback, and recovery for P09.

baseline = model(5,6,true,true,'none','none','strict-order');
assertSequenceInvariant(baseline);

expectedStartupActions = { ...
    'assert-command-inhibit', ...
    'energize-power', ...
    'boot-controller', ...
    'qualify-p08-interface', ...
    'enable-actuator', ...
    'release-command-inhibit'};
expectedShutdownActions = { ...
    'inhibit-new-commands', ...
    'command-safe-output', ...
    'disable-actuator', ...
    'confirm-quiescence', ...
    'close-p08-interface', ...
    'remove-power'};
expectedRollbackActions = { ...
    'inhibit-new-commands', ...
    'command-safe-output', ...
    'disable-actuator', ...
    'confirm-quiescence-and-isolate', ...
    'remove-power'};
expectedStateNames = { ...
    'Power on', ...
    'Controller online', ...
    'P08 interface qualified', ...
    'Actuator enabled', ...
    'Command inhibited', ...
    'Safe command asserted', ...
    'Quiescence confirmed'};
expectedStartupTrace = [ ...
    0 0 0 0 1 1 1; ...
    1 0 0 0 1 1 1; ...
    1 1 0 0 1 1 1; ...
    1 1 1 0 1 1 1; ...
    1 1 1 1 1 1 0; ...
    1 1 1 1 0 0 0];
expectedShutdownTrace = [ ...
    1 1 1 1 1 0 0; ...
    1 1 1 1 1 1 0; ...
    1 1 1 0 1 1 0; ...
    1 1 1 0 1 1 1; ...
    1 1 0 0 1 1 1; ...
    0 0 0 0 1 1 1];

assert(isequal(baseline.startupActionNames,expectedStartupActions) && ...
    isequal(baseline.shutdownActionNames,expectedShutdownActions) && ...
    isequal(baseline.rollbackActionNames,expectedRollbackActions) && ...
    isequal(baseline.stateNames,expectedStateNames), ...
    'Baseline action or state identity changed.');
assert(isequal(baseline.startupStateTrace,expectedStartupTrace) && ...
    isequal(baseline.shutdownStateTrace,expectedShutdownTrace), ...
    'Baseline state recurrence differs from the independent trace.');
assert(all(baseline.startupActionEvaluated) && ...
    all(baseline.startupPreconditionPass) && ...
    all(baseline.startupPostconditionPass) && ...
    all(baseline.startupStepPass) && ...
    ~any(baseline.startupHazard) && ...
    all(baseline.shutdownActionEvaluated) && ...
    all(baseline.shutdownPreconditionPass) && ...
    all(baseline.shutdownPostconditionPass) && ...
    all(baseline.shutdownStepPass) && ...
    ~any(baseline.shutdownHazard), ...
    'Every baseline action must prove its guard and effect.');
assert(isequal(baseline.startupEnablePrerequisitePass, ...
    true(1,6)) && baseline.startupEnableMissingPrerequisiteCount == 0 && ...
    isequal(baseline.shutdownPowerPrerequisitePass, ...
    true(1,5)) && baseline.shutdownPowerMissingPrerequisiteCount == 0, ...
    'The two baseline safety-sensitive actions must have no missing facts.');
assert(isequal(baseline.startupFinalState,[1 1 1 1 0 0 0]) && ...
    baseline.startupFinalRunning && baseline.startupOrderValid && ...
    isequal(baseline.shutdownFinalState,[0 0 0 0 1 1 1]) && ...
    baseline.shutdownFinalSafeOff && baseline.shutdownOrderValid && ...
    baseline.sequenceEvaluated && baseline.strictLifecycleAccepted && ...
    baseline.snapshotLifecycleAccepted && ...
    baseline.reportedLifecycleAccepted && ...
    baseline.assessmentDecisionCorrect && ~baseline.falseApproval && ...
    baseline.totalViolationCount == 0 && ...
    strcmp(baseline.terminalStatus,'completed-safe-off') && ...
    strcmp(baseline.failureMode,'none'), ...
    'Baseline lifecycle acceptance or terminal changed.');

expectedStartupMissing = [3 3 2 1 0];
expectedStartupStrict = [false false false false true];
for position = 1:5
    candidate = model(position,6,true,true, ...
        'none','none','strict-order');
    assertSequenceInvariant(candidate);
    assert(strcmp(candidate.startupActionNames{position}, ...
        'enable-actuator') && ...
        candidate.startupEnableMissingPrerequisiteCount == ...
        expectedStartupMissing(position) && ...
        candidate.strictLifecycleAccepted == ...
        expectedStartupStrict(position) && ...
        candidate.startupFinalRunning && ...
        candidate.shutdownFinalSafeOff && ...
        candidate.inputs.shutdownPowerOffPosition == 6, ...
        'Startup sweep must isolate actuator-enable position and its guards.');
end
startupMinimum = model(1,6,true,true,'none','none','strict-order');
startupJustBeforeValid = model(4,6,true,true, ...
    'none','none','strict-order');
startupValidLimit = model(5,6,true,true,'none','none','strict-order');
assert(startupMinimum.startupEnableMissingPrerequisiteCount == 3 && ...
    strcmp(startupMinimum.failureMode, ...
    'startup-enable-before-prerequisites') && ...
    startupJustBeforeValid.startupEnableMissingPrerequisiteCount == 1 && ...
    ~startupJustBeforeValid.strictLifecycleAccepted && ...
    startupValidLimit.startupEnableMissingPrerequisiteCount == 0 && ...
    startupValidLimit.strictLifecycleAccepted, ...
    'Startup limiting positions must reject 4 and accept 5.');

expectedShutdownMissing = [5 4 3 2 1 0];
expectedShutdownStrict = [false false false false false true];
for position = 1:6
    candidate = model(5,position,true,true, ...
        'none','none','strict-order');
    assertSequenceInvariant(candidate);
    assert(strcmp(candidate.shutdownActionNames{position}, ...
        'remove-power') && ...
        candidate.shutdownPowerMissingPrerequisiteCount == ...
        expectedShutdownMissing(position) && ...
        candidate.strictLifecycleAccepted == ...
        expectedShutdownStrict(position) && ...
        candidate.startupFinalRunning && ...
        candidate.shutdownFinalSafeOff && ...
        candidate.inputs.startupEnablePosition == 5, ...
        'Shutdown sweep must isolate power-removal position and its guards.');
end
shutdownMinimum = model(5,1,true,true,'none','none','strict-order');
shutdownJustBeforeValid = model(5,5,true,true, ...
    'none','none','strict-order');
shutdownValidLimit = model(5,6,true,true,'none','none','strict-order');
assert(shutdownMinimum.shutdownPowerMissingPrerequisiteCount == 5 && ...
    shutdownMinimum.unsafePowerRemoval && ...
    strcmp(shutdownMinimum.failureMode,'power-removed-before-safe') && ...
    shutdownJustBeforeValid.shutdownPowerMissingPrerequisiteCount == 1 && ...
    shutdownJustBeforeValid.unsafePowerRemoval && ...
    ~shutdownJustBeforeValid.strictLifecycleAccepted && ...
    shutdownValidLimit.shutdownPowerMissingPrerequisiteCount == 0 && ...
    ~shutdownValidLimit.unsafePowerRemoval && ...
    shutdownValidLimit.strictLifecycleAccepted, ...
    'Shutdown limiting positions must reject 5 and accept 6.');

contractInvalid = model(5,6,false,false,'none','none','strict-order');
inputWithheld = model(5,6,true,false,'none','none','strict-order');
assertSequenceInvariant(contractInvalid);
assertSequenceInvariant(inputWithheld);
assert(~contractInvalid.startupFinalRunning && ...
    ~contractInvalid.startupOrderValid && ...
    strcmp(contractInvalid.failureMode,'p08-contract-not-conformant') && ...
    ~inputWithheld.startupFinalRunning && ...
    inputWithheld.startupEnablePrerequisitePass(3) && ...
    ~inputWithheld.startupEnablePrerequisitePass(4) && ...
    strcmp(inputWithheld.failureMode,'p08-input-not-eligible'), ...
    'P08 conformance and quality-gated eligibility must remain distinct.');

actuatorStuck = model(5,6,true,true, ...
    'actuator-stuck-on','none','strict-order');
quiescenceMissing = model(5,6,true,true, ...
    'quiescence-not-confirmed','none','strict-order');
for candidate = {actuatorStuck,quiescenceMissing}
    assertSequenceInvariant(candidate{1});
    assert(candidate{1}.sequenceEvaluated && ...
        candidate{1}.startupOrderValid && ...
        candidate{1}.startupFinalRunning && ...
        ~candidate{1}.shutdownOrderValid && ...
        ~candidate{1}.shutdownFinalSafeOff && ...
        candidate{1}.unsafePowerRemoval && ...
        ~candidate{1}.strictLifecycleAccepted && ...
        strcmp(candidate{1}.terminalStatus,'completed-with-hazard'), ...
        'Shutdown faults must retain startup truth and fail safe-off proof.');
end
assert(actuatorStuck.shutdownPostconditionPass(3) == false && ...
    actuatorStuck.shutdownFinalState(4) == 1 && ...
    strcmp(actuatorStuck.failureMode,'actuator-disable-failed'), ...
    'A stuck actuator must fail disable before later quiescence checks.');
assert(quiescenceMissing.shutdownPostconditionPass(4) == false && ...
    quiescenceMissing.shutdownFinalState(7) == 0 && ...
    strcmp(quiescenceMissing.failureMode,'quiescence-not-confirmed'), ...
    'Missing quiescence must remain separate from actuator disable.');

cancelled = model(5,6,true,true,'none','cancellation','strict-order');
timedOut = model(5,6,true,true,'none','timeout','strict-order');
tied = model(5,6,true,true,'none', ...
    'cancellation-timeout-tie','strict-order');
timeoutBeforeContract = model(5,6,false,false, ...
    'none','timeout','strict-order');
eventAfterEarlyEnable = model(1,1,true,true, ...
    'none','cancellation','final-state-only');
expectedEvaluatedBeforeEvent = [true true true false false false];
expectedRollbackTrace = [ ...
    1 1 0 0 1 1 1; ...
    1 1 0 0 1 1 1; ...
    1 1 0 0 1 1 1; ...
    1 0 0 0 1 1 1; ...
    0 0 0 0 1 1 1];
for candidate = {cancelled,timedOut,tied,timeoutBeforeContract}
    out = candidate{1};
    assertSequenceInvariant(out);
    assert(isequal(out.startupActionEvaluated, ...
        expectedEvaluatedBeforeEvent) && ...
        all(all(isfinite(out.startupStateTrace(1:3,:)))) && ...
        all(all(isnan(out.startupStateTrace(4:6,:)))) && ...
        isnan(out.startupEnableMissingPrerequisiteCount) && ...
        ~any(out.shutdownActionEvaluated) && ...
        all(all(isnan(out.shutdownStateTrace))) && ...
        isnan(out.shutdownPowerMissingPrerequisiteCount) && ...
        all(isnan(out.shutdownFinalState)) && ...
        out.rollbackPerformed && out.rollbackSafeHold && ...
        all(out.rollbackActionExecuted) && ...
        all(out.rollbackPreconditionPass) && ...
        all(out.rollbackPostconditionPass) && ...
        all(out.rollbackStepPass) && ~any(out.rollbackHazard) && ...
        isequal(out.rollbackStateTrace,expectedRollbackTrace) && ...
        strcmp(out.rollbackFailureMode,'none') && ...
        ~out.sequenceEvaluated && ~out.reportedLifecycleAccepted && ...
        ~out.assessmentDecisionCorrect && out.terminalOutcomeHandled, ...
        'Injected startup events must mask downstream facts and roll back.');
end
assert(cancelled.cancellationObserved && ~cancelled.timeoutObserved && ...
    strcmp(cancelled.terminalStatus,'cancelled-safe-hold') && ...
    strcmp(cancelled.failureMode,'startup-cancelled'), ...
    'Cancellation must terminate in modeled safe hold.');
assert(~timedOut.cancellationObserved && timedOut.timeoutObserved && ...
    strcmp(timedOut.terminalStatus,'timed-out-safe-hold') && ...
    strcmp(timedOut.failureMode,'startup-timeout'), ...
    'Timeout must remain a distinguishable asserted event.');
assert(tied.cancellationObserved && tied.timeoutObserved && ...
    tied.tieResolvedToCancellation && ...
    strcmp(tied.terminalStatus,'cancelled-safe-hold') && ...
    strcmp(tied.failureMode,'startup-cancelled'), ...
    'Cancellation must win the modeled cancellation/timeout tie.');
assert(strcmp(timeoutBeforeContract.failureMode,'startup-timeout'), ...
    'An event before interface qualification must precede P08 diagnosis.');
assertSequenceInvariant(eventAfterEarlyEnable);
assert(eventAfterEarlyEnable.rollbackSafeHold && ...
    eventAfterEarlyEnable.startupViolationCount >= 1 && ...
    ~eventAfterEarlyEnable.reportedLifecycleAccepted, ...
    'Rollback must contain an early-enable proposal without snapshot approval.');

cancelledStuck = model(1,6,true,true, ...
    'actuator-stuck-on','cancellation','strict-order');
timedOutNoQuiescence = model(5,6,true,true, ...
    'quiescence-not-confirmed','timeout','strict-order');
tiedNoQuiescence = model(5,6,true,true, ...
    'quiescence-not-confirmed','cancellation-timeout-tie', ...
    'strict-order');
assertSequenceInvariant(cancelledStuck);
assertSequenceInvariant(timedOutNoQuiescence);
assertSequenceInvariant(tiedNoQuiescence);
assert(cancelledStuck.rollbackPerformed && ...
    ~cancelledStuck.rollbackSafeHold && ...
    cancelledStuck.rollbackViolationCount >= 1 && ...
    ~cancelledStuck.rollbackPostconditionPass(3) && ...
    cancelledStuck.rollbackHazard(3) && ...
    isequal(cancelledStuck.rollbackStateTrace(end,:), ...
    [0 0 0 1 1 1 0]) && ...
    strcmp(cancelledStuck.terminalStatus, ...
    'cancelled-rollback-incomplete') && ...
    strcmp(cancelledStuck.rollbackFailureMode, ...
    'actuator-disable-failed'), ...
    'Cancellation plus a stuck actuator must expose incomplete rollback.');
assert(timedOutNoQuiescence.rollbackPerformed && ...
    ~timedOutNoQuiescence.rollbackSafeHold && ...
    timedOutNoQuiescence.rollbackViolationCount >= 1 && ...
    ~timedOutNoQuiescence.rollbackPostconditionPass(4) && ...
    timedOutNoQuiescence.rollbackHazard(4) && ...
    isequal(timedOutNoQuiescence.rollbackStateTrace(end,:), ...
    [0 0 0 0 1 1 0]) && ...
    strcmp(timedOutNoQuiescence.terminalStatus, ...
    'timed-out-rollback-incomplete') && ...
    strcmp(timedOutNoQuiescence.rollbackFailureMode, ...
    'quiescence-not-confirmed'), ...
    'Timeout plus missing quiescence must expose incomplete rollback.');
assert(tiedNoQuiescence.cancellationObserved && ...
    tiedNoQuiescence.timeoutObserved && ...
    tiedNoQuiescence.tieResolvedToCancellation && ...
    ~tiedNoQuiescence.rollbackSafeHold && ...
    strcmp(tiedNoQuiescence.terminalStatus, ...
    'cancelled-rollback-incomplete') && ...
    strcmp(tiedNoQuiescence.failureMode,'startup-cancelled') && ...
    strcmp(tiedNoQuiescence.rollbackFailureMode, ...
    'quiescence-not-confirmed') && ...
    all(isnan(tiedNoQuiescence.shutdownFinalState)), ...
    'Cancellation must retain tie precedence when rollback is incomplete.');

brokenScenarios = [1 6; 5 1; 1 1];
for k = 1:size(brokenScenarios,1)
    enablePosition = brokenScenarios(k,1);
    powerPosition = brokenScenarios(k,2);
    strict = model(enablePosition,powerPosition,true,true, ...
        'none','none','strict-order');
    broken = model(enablePosition,powerPosition,true,true, ...
        'none','none','final-state-only');
    assertSequenceInvariant(strict);
    assertSequenceInvariant(broken);
    assert(isequal(strict.startupActionNames,broken.startupActionNames) && ...
        isequal(strict.shutdownActionNames,broken.shutdownActionNames) && ...
        isequaln(strict.startupStateTrace,broken.startupStateTrace) && ...
        isequaln(strict.shutdownStateTrace,broken.shutdownStateTrace) && ...
        isequal(strict.startupStepPass,broken.startupStepPass) && ...
        isequal(strict.shutdownStepPass,broken.shutdownStepPass) && ...
        strict.startupFinalRunning == broken.startupFinalRunning && ...
        strict.shutdownFinalSafeOff == broken.shutdownFinalSafeOff && ...
        strict.strictLifecycleAccepted == ...
        broken.strictLifecycleAccepted && ...
        ~strict.reportedLifecycleAccepted && ...
        broken.snapshotLifecycleAccepted && ...
        broken.reportedLifecycleAccepted && broken.falseApproval && ...
        ~broken.assessmentDecisionCorrect && ...
        strcmp(broken.reportingFailureMode, ...
        'final-state-only-false-approval'), ...
        'Broken assessment must change reporting without changing facts.');
end
brokenBaseline = model(5,6,true,true, ...
    'none','none','final-state-only');
brokenContract = model(5,6,false,false, ...
    'none','none','final-state-only');
assertSequenceInvariant(brokenBaseline);
assertSequenceInvariant(brokenContract);
assert(brokenBaseline.reportedLifecycleAccepted && ...
    brokenBaseline.strictLifecycleAccepted && ...
    ~brokenBaseline.falseApproval && ...
    brokenBaseline.assessmentDecisionCorrect && ...
    ~brokenContract.snapshotLifecycleAccepted && ...
    ~brokenContract.reportedLifecycleAccepted && ...
    ~brokenContract.falseApproval, ...
    'Snapshot assessment must not fabricate a missing final configuration.');

compatible = model(int8(5),uint8(6),uint8(1),logical(1), ...
    string(' NONE '),string(' NONE '),string(' STRICT-ORDER '));
assert(isequaln(compatible,baseline), ...
    'Compatible numeric, logical, and scalar-text inputs must normalize.');

expectErrorId(@() model(0,6,true,true,'none','none','strict-order'), ...
    'P09:InvalidStartupEnablePosition');
expectAnyError(@() model(6,6,true,true,'none','none','strict-order'));
expectAnyError(@() model(4.5,6,true,true,'none','none','strict-order'));
expectAnyError(@() model(NaN,6,true,true,'none','none','strict-order'));
expectAnyError(@() model(Inf,6,true,true,'none','none','strict-order'));
expectAnyError(@() model(1+1i,6,true,true,'none','none','strict-order'));
expectAnyError(@() model([4 5],6,true,true,'none','none','strict-order'));
expectAnyError(@() model('5',6,true,true,'none','none','strict-order'));
expectErrorId(@() model(5,0,true,true,'none','none','strict-order'), ...
    'P09:InvalidShutdownPowerOffPosition');
expectAnyError(@() model(5,7,true,true,'none','none','strict-order'));
expectAnyError(@() model(5,5.5,true,true,'none','none','strict-order'));
expectAnyError(@() model(5,[5 6],true,true,'none','none','strict-order'));
expectErrorId(@() model(5,6,2,true,'none','none','strict-order'), ...
    'P09:InvalidP08Conformance');
expectAnyError(@() model(5,6,[true false],true, ...
    'none','none','strict-order'));
expectAnyError(@() model(5,6,'true',true,'none','none','strict-order'));
expectErrorId(@() model(5,6,true,2,'none','none','strict-order'), ...
    'P09:InvalidP08Eligibility');
expectAnyError(@() model(5,6,true,[true false], ...
    'none','none','strict-order'));
expectErrorId(@() model(5,6,false,true,'none','none','strict-order'), ...
    'P09:InconsistentP08Facts');
expectErrorId(@() model(5,6,true,true,'sensor-open', ...
    'none','strict-order'),'P09:InvalidFaultMode');
expectErrorId(@() model(5,6,true,true,'none', ...
    'deadline','strict-order'),'P09:InvalidEventMode');
expectErrorId(@() model(5,6,true,true,'none', ...
    'none','trust-snapshot'),'P09:InvalidAssessmentMode');
expectAnyError(@() model(5,6,true,true,1,'none','strict-order'));
expectAnyError(@() model(5,6,true,true, ...
    string({'none','actuator-stuck-on'}),'none','strict-order'));

afterMalformed = model(5,6,true,true,'none','none','strict-order');
afterEarlyEnable = model(5,6,true,true,'none','none','strict-order');
afterEarlyPower = model(5,6,true,true,'none','none','strict-order');
afterContract = model(5,6,true,true,'none','none','strict-order');
afterFault = model(5,6,true,true,'none','none','strict-order');
afterCancellation = model(5,6,true,true,'none','none','strict-order');
afterTimeout = model(5,6,true,true,'none','none','strict-order');
afterBroken = model(5,6,true,true,'none','none','strict-order');
assert(isequaln(afterMalformed,baseline) && ...
    isequaln(afterEarlyEnable,baseline) && ...
    isequaln(afterEarlyPower,baseline) && ...
    isequaln(afterContract,baseline) && ...
    isequaln(afterFault,baseline) && ...
    isequaln(afterCancellation,baseline) && ...
    isequaln(afterTimeout,baseline) && ...
    isequaln(afterBroken,baseline), ...
    'Every valid call after failure, event, or malformed input must recover.');

disp('P09 checks passed: ordering, P08 compatibility, limits, events, rollback, recovery, isolation, and broken assessment.');
end

function assertSequenceInvariant(out)
assert(out.actionCount == 6 && out.stateCount == 7 && ...
    out.rollbackActionCount == 5 && out.eventCheckpointAction == 3 && ...
    numel(out.startupActionNames) == 6 && ...
    numel(out.shutdownActionNames) == 6 && ...
    numel(out.rollbackActionNames) == 5 && ...
    numel(out.stateNames) == 7 && ...
    numel(out.rollbackActionExecuted) == 5 && ...
    numel(out.rollbackPreconditionPass) == 5 && ...
    numel(out.rollbackPostconditionPass) == 5 && ...
    numel(out.rollbackStepPass) == 5 && ...
    numel(out.rollbackHazard) == 5 && ...
    isequal(size(out.startupStateTrace),[6 7]) && ...
    isequal(size(out.shutdownStateTrace),[6 7]) && ...
    isequal(size(out.rollbackStateTrace),[5 7]), ...
    'Every result must remain inside the fixed resource envelope.');
assert(strcmp(out.startupActionNames{ ...
    out.inputs.startupEnablePosition},'enable-actuator') && ...
    strcmp(out.shutdownActionNames{ ...
    out.inputs.shutdownPowerOffPosition},'remove-power'), ...
    'Each lever must move only its owned action.');

startupEvaluated = out.startupActionEvaluated;
shutdownEvaluated = out.shutdownActionEvaluated;
assert(all(all(isfinite(out.startupStateTrace(startupEvaluated,:)))) && ...
    all(all(isnan(out.startupStateTrace(~startupEvaluated,:)))) && ...
    ~any(out.startupPreconditionPass(~startupEvaluated)) && ...
    ~any(out.startupPostconditionPass(~startupEvaluated)) && ...
    ~any(out.startupStepPass(~startupEvaluated)) && ...
    ~any(out.startupHazard(~startupEvaluated)), ...
    'Unevaluated startup rows must expose no result or state.');
assert(all(all(isfinite(out.shutdownStateTrace(shutdownEvaluated,:)))) && ...
    all(all(isnan(out.shutdownStateTrace(~shutdownEvaluated,:)))) && ...
    ~any(out.shutdownPreconditionPass(~shutdownEvaluated)) && ...
    ~any(out.shutdownPostconditionPass(~shutdownEvaluated)) && ...
    ~any(out.shutdownStepPass(~shutdownEvaluated)) && ...
    ~any(out.shutdownHazard(~shutdownEvaluated)), ...
    'Unevaluated shutdown rows must expose no result or state.');
assert(isequal(out.startupStepPass, ...
    out.startupActionEvaluated & out.startupPreconditionPass & ...
    out.startupPostconditionPass) && ...
    isequal(out.startupHazard, ...
    out.startupActionEvaluated & ~out.startupStepPass) && ...
    isequal(out.shutdownStepPass, ...
    out.shutdownActionEvaluated & out.shutdownPreconditionPass & ...
    out.shutdownPostconditionPass) && ...
    isequal(out.shutdownHazard, ...
    out.shutdownActionEvaluated & ~out.shutdownStepPass), ...
    'Step and hazard flags must derive from evaluated guards and effects.');

enableEvaluated = out.startupActionEvaluated( ...
    out.inputs.startupEnablePosition);
if enableEvaluated
    assert(out.startupEnableMissingPrerequisiteCount == ...
        sum(~out.startupEnablePrerequisitePass), ...
        'Enable missing count must equal its six visible prerequisite facts.');
else
    assert(isnan(out.startupEnableMissingPrerequisiteCount) && ...
        ~any(out.startupEnablePrerequisitePass), ...
        'Skipped enable must expose no prerequisite count.');
end
powerRemovalEvaluated = out.shutdownActionEvaluated( ...
    out.inputs.shutdownPowerOffPosition);
if powerRemovalEvaluated
    assert(out.shutdownPowerMissingPrerequisiteCount == ...
        sum(~out.shutdownPowerPrerequisitePass) && ...
        out.unsafePowerRemoval == ...
        ~all(out.shutdownPowerPrerequisitePass), ...
        'Power-removal missing count must equal its five visible facts.');
else
    assert(isnan(out.shutdownPowerMissingPrerequisiteCount) && ...
        ~any(out.shutdownPowerPrerequisitePass) && ...
        ~out.unsafePowerRemoval, ...
        'Skipped power removal must expose no prerequisite result.');
end

assert(out.eventObserved == ...
    (out.cancellationObserved || out.timeoutObserved) && ...
    out.tieResolvedToCancellation == ...
    strcmp(out.inputs.eventMode,'cancellation-timeout-tie'), ...
    'Event facts and tie precedence must derive from the injected input.');
if out.eventObserved
    assert(out.rollbackPerformed && ...
        all(out.rollbackActionExecuted) && ...
        all(all(isfinite(out.rollbackStateTrace))) && ...
        all(isnan(out.shutdownFinalState)) && ...
        ~out.shutdownCompleted && ~out.sequenceEvaluated, ...
        'An event must execute fixed rollback and isolate nominal shutdown.');
    assert(isequal(out.rollbackStepPass, ...
        out.rollbackActionExecuted & out.rollbackPreconditionPass & ...
        out.rollbackPostconditionPass) && ...
        isequal(out.rollbackHazard, ...
        out.rollbackActionExecuted & ~out.rollbackStepPass), ...
        'Rollback flags must derive from executed guards and effects.');
    finalSafeHold = isequal(out.rollbackStateTrace(end,:), ...
        [0 0 0 0 1 1 1]);
    assert(out.rollbackSafeHold == ...
        (all(out.rollbackStepPass) && finalSafeHold), ...
        'Rollback safe hold requires every step and the modeled final facts.');
else
    assert(~out.rollbackPerformed && ~out.rollbackSafeHold && ...
        ~any(out.rollbackActionExecuted) && ...
        ~any(out.rollbackPreconditionPass) && ...
        ~any(out.rollbackPostconditionPass) && ...
        ~any(out.rollbackStepPass) && ~any(out.rollbackHazard) && ...
        all(all(isnan(out.rollbackStateTrace))) && ...
        strcmp(out.rollbackFailureMode,'none') && ...
        all(isfinite(out.shutdownFinalState)) && ...
        out.startupCompleted && out.shutdownCompleted && ...
        out.sequenceEvaluated, ...
        'A nominal proposal must evaluate both phases without rollback.');
end

assert(out.startupOrderValid == ...
    (out.startupCompleted && all(out.startupStepPass)) && ...
    out.shutdownOrderValid == ...
    (out.shutdownCompleted && all(out.shutdownStepPass)) && ...
    out.strictLifecycleAccepted == ...
    (out.sequenceEvaluated && out.startupOrderValid && ...
    out.startupFinalRunning && out.shutdownOrderValid && ...
    out.shutdownFinalSafeOff) && ...
    out.snapshotLifecycleAccepted == ...
    (out.sequenceEvaluated && out.startupFinalRunning && ...
    out.shutdownFinalSafeOff), ...
    'Strict and snapshot truth must retain separate equations.');
if strcmp(out.inputs.assessmentMode,'strict-order')
    assert(out.reportedLifecycleAccepted == ...
        out.strictLifecycleAccepted, ...
        'Strict reporting must retain all ordered evidence.');
else
    assert(out.reportedLifecycleAccepted == ...
        out.snapshotLifecycleAccepted, ...
        'Broken reporting must inspect final snapshots only.');
end
assert(out.falseApproval == ...
    (out.sequenceEvaluated && out.reportedLifecycleAccepted && ...
    ~out.strictLifecycleAccepted) && ...
    out.assessmentDecisionCorrect == ...
    (out.sequenceEvaluated && ...
    (out.reportedLifecycleAccepted == out.strictLifecycleAccepted)) && ...
    out.startupViolationCount == ...
    sum(out.startupActionEvaluated & ~out.startupStepPass) && ...
    out.shutdownViolationCount == ...
    sum(out.shutdownActionEvaluated & ~out.shutdownStepPass) && ...
    out.rollbackViolationCount == ...
    sum(out.rollbackActionExecuted & ~out.rollbackStepPass) && ...
    out.totalViolationCount == ...
    out.startupViolationCount + out.shutdownViolationCount + ...
    out.rollbackViolationCount && ...
    out.terminalOutcomeHandled, ...
    'Reporting, violations, and terminal handling must remain traceable.');
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
