function run_checks
%RUN_CHECKS Independent P07 measurement value, quality, and path checks.
baseline = model(30,12,5,20,'none','none','complete');
repeat = model(30,12,5,20,'none','none','complete');
defaults = model();
assert(isequaln(baseline,repeat) && isequaln(defaults,baseline), ...
    'Repeated and default baseline calls must be deterministic and stateless.');
assertTraceInvariant(baseline);

expectedStageNames = { ...
    'Observe position sensor', ...
    'Digitize sensor voltage', ...
    'Calibrate to engineering units', ...
    'Qualify sample', ...
    'P07 qualified-control intake'};
expectedStageOwners = { ...
    'sensor-hardware', ...
    'acquisition-hardware', ...
    'hardware-interface', ...
    'measurement-supervision', ...
    'control-software'};
expectedStageUnits = {'V','count','deg','deg','deg'};
expectedBoundaryNames = { ...
    'sensor-to-adc', ...
    'adc-to-calibration', ...
    'calibration-to-quality', ...
    'quality-to-controller'};
assert(isequal(baseline.stageNames,expectedStageNames) && ...
    isequal(baseline.stageOwners,expectedStageOwners) && ...
    isequal(baseline.stageUnits,expectedStageUnits) && ...
    isequal(baseline.boundaryNames,expectedBoundaryNames), ...
    'P07 must preserve the declared stage, owner, unit, and boundary map.');
assert(baseline.stageCount == 5 && baseline.boundaryCount == 4 && ...
    baseline.minimumAdcBits == 4 && baseline.maximumAdcBits == 16 && ...
    baseline.maxAgeMs == 10000 && baseline.maxPhysicalAngleDeg == 360 && ...
    isequal(size(baseline.stageReached),[1 5]) && ...
    isequal(size(baseline.stageOutputValue),[1 5]) && ...
    isequal(size(baseline.boundaryCrossed),[1 4]), ...
    'The fixed five-stage, four-boundary resource envelope changed.');

expectedSensorVolts = 2.5 + 30/90;
expectedMaxAdcCount = 2^12 - 1;
expectedAdcCount = round((expectedSensorVolts - 0.5)/4*expectedMaxAdcCount);
expectedAngleDeg = -180 + 360*expectedAdcCount/expectedMaxAdcCount;
expectedQuantizationStepDeg = 360/expectedMaxAdcCount;
assert(abs(baseline.sensorVolts - expectedSensorVolts) < 1e-12 && ...
    baseline.maxAdcCount == expectedMaxAdcCount && ...
    baseline.adcCount == expectedAdcCount && ...
    abs(baseline.calibratedAngleDeg - expectedAngleDeg) < 1e-12 && ...
    abs(baseline.quantizationStepDeg - expectedQuantizationStepDeg) < 1e-12 && ...
    abs(baseline.quantizationErrorDeg) <= ...
    baseline.quantizationBoundDeg + 1e-12, ...
    'Baseline values must follow independent sensor, ADC, and calibration equations.');
assert(all(baseline.stageReached) && all(baseline.boundaryAttempted) && ...
    all(baseline.boundaryCrossed) && ~any(baseline.boundaryOpen) && ...
    baseline.deepestReachedStage == 5 && baseline.crossedBoundaryCount == 4 && ...
    baseline.entryPermitted && ~baseline.eventObserved && ...
    ~baseline.sensorSaturated && baseline.freshnessCriterionMet && ...
    baseline.freshnessMarginMs == 15 && baseline.qualityEvaluated && ...
    baseline.qualityValid && baseline.endpointReceived && ...
    baseline.endpointQualityValid && baseline.measurementUsable && ...
    baseline.payloadPreservedToEndpoint && ...
    baseline.qualityFlagPreservedToEndpoint && ...
    baseline.p06InputEligible && baseline.p06ScalarAdapterMet && ...
    baseline.p06ObservedAngleDeg == baseline.stageOutputValue(5) && ...
    baseline.reportedUsable && ~baseline.falseUsable && ...
    baseline.terminalOutcomeHandled && baseline.traceContractMet && ...
    strcmp(baseline.terminalStatus,'delivered-valid') && ...
    strcmp(baseline.failureMode,'none'), ...
    'The valid baseline must deliver an exact value and valid quality flag.');

adcBitChoices = [6 8 10 12];
expectedAdcCounts = [37 149 597 2389];
previousStepDeg = Inf;
for k = 1:numel(adcBitChoices)
    candidate = model(30,adcBitChoices(k),5,20, ...
        'none','none','complete');
    assertTraceInvariant(candidate);
    independentMaxCount = 2^adcBitChoices(k) - 1;
    independentCount = round(((2.5 + 30/90) - 0.5)/4* ...
        independentMaxCount);
    independentAngleDeg = -180 + 360*independentCount/independentMaxCount;
    assert(candidate.adcCount == expectedAdcCounts(k) && ...
        candidate.adcCount == independentCount && ...
        abs(candidate.calibratedAngleDeg - independentAngleDeg) < 1e-12 && ...
        abs(candidate.quantizationErrorDeg) <= ...
        0.5*candidate.quantizationStepDeg + 1e-12 && ...
        candidate.quantizationStepDeg < previousStepDeg, ...
        'Every ADC choice must follow the transparent count and half-LSB bound.');
    previousStepDeg = candidate.quantizationStepDeg;
end
minimumResolution = model(30,4,5,20,'none','none','complete');
maximumResolution = model(30,16,5,20,'none','none','complete');
assertTraceInvariant(minimumResolution);
assertTraceInvariant(maximumResolution);
assert(minimumResolution.maxAdcCount == 15 && ...
    maximumResolution.maxAdcCount == 65535 && ...
    minimumResolution.adcCount >= 0 && ...
    minimumResolution.adcCount <= minimumResolution.maxAdcCount && ...
    maximumResolution.adcCount >= 0 && ...
    maximumResolution.adcCount <= maximumResolution.maxAdcCount && ...
    maximumResolution.quantizationStepDeg < ...
    minimumResolution.quantizationStepDeg, ...
    'Minimum and maximum ADC settings must remain inside the resource bound.');

zeroAngle = model(0,12,5,20,'none','none','complete');
negativeAngle = model(-30,12,5,20,'none','none','complete');
negativeFullScale = model(-180,12,5,20,'none','none','complete');
positiveFullScale = model(180,12,5,20,'none','none','complete');
for candidate = {zeroAngle,negativeAngle,negativeFullScale,positiveFullScale}
    assertTraceInvariant(candidate{1});
end
assert(abs(zeroAngle.quantizationErrorDeg) <= ...
    zeroAngle.quantizationBoundDeg + 1e-12 && zeroAngle.measurementUsable, ...
    'The zero-angle half-LSB case must remain bounded and usable.');
assert(abs(negativeAngle.calibratedAngleDeg + ...
    baseline.calibratedAngleDeg) < 1e-12 && negativeAngle.measurementUsable, ...
    'Signed angles must mirror through the symmetric measurement chain.');
assert(negativeFullScale.adcCount == 0 && ...
    negativeFullScale.calibratedAngleDeg == -180 && ...
    ~negativeFullScale.sensorSaturated && negativeFullScale.measurementUsable && ...
    positiveFullScale.adcCount == positiveFullScale.maxAdcCount && ...
    positiveFullScale.calibratedAngleDeg == 180 && ...
    ~positiveFullScale.sensorSaturated && positiveFullScale.measurementUsable, ...
    'Exact sensor full-scale endpoints must be valid inclusive limits.');

justSaturated = model(180.001,12,5,20,'none','none','complete');
maxBounded = model(360,12,5,20,'none','none','complete');
negativeJustSaturated = model(-180.001,12,5,20, ...
    'none','none','complete');
negativeMaxBounded = model(-360,12,5,20,'none','none','complete');
for candidate = {justSaturated,maxBounded,negativeJustSaturated, ...
        negativeMaxBounded}
    assertTraceInvariant(candidate{1});
    assert(candidate{1}.endpointReceived && candidate{1}.sensorSaturated && ...
        candidate{1}.qualityEvaluated && ~candidate{1}.qualityValid && ...
        ~candidate{1}.measurementUsable && ~candidate{1}.reportedUsable && ...
        strcmp(candidate{1}.terminalStatus,'delivered-invalid') && ...
        strcmp(candidate{1}.failureMode,'sensor-saturated'), ...
        'Out-of-range truth must produce a received but invalid saturated sample.');
end
assert(maxBounded.adcCount == maxBounded.maxAdcCount && ...
    maxBounded.calibratedAngleDeg == 180 && ...
    negativeJustSaturated.adcCount == 0 && ...
    negativeMaxBounded.adcCount == 0 && ...
    negativeMaxBounded.calibratedAngleDeg == -180, ...
    'Both bounded input extremes must clip to the declared sensor full scale.');

ageAtLimit = model(30,12,20,20,'none','none','complete');
ageJustOver = model(30,12,20.001,20,'none','none','complete');
zeroAgeZeroLimit = model(30,12,0,0,'none','none','complete');
nonzeroAgeZeroLimit = model(30,12,0.001,0,'none','none','complete');
maxAgeAtLimit = model(30,12,10000,10000,'none','none','complete');
for candidate = {ageAtLimit,ageJustOver,zeroAgeZeroLimit, ...
        nonzeroAgeZeroLimit,maxAgeAtLimit}
    assertTraceInvariant(candidate{1});
end
assert(ageAtLimit.freshnessCriterionMet && ageAtLimit.qualityValid && ...
    ageAtLimit.measurementUsable && ageAtLimit.freshnessMarginMs == 0 && ...
    zeroAgeZeroLimit.measurementUsable && maxAgeAtLimit.measurementUsable, ...
    'Freshness equality must pass at zero, nominal, and maximum bounded age.');
assert(~ageJustOver.freshnessCriterionMet && ~ageJustOver.qualityValid && ...
    ageJustOver.endpointReceived && ~ageJustOver.measurementUsable && ...
    strcmp(ageJustOver.failureMode,'stale-sample') && ...
    ~nonzeroAgeZeroLimit.measurementUsable, ...
    'A sample just beyond its supplied limit must be stale without disappearing.');
assert(ageAtLimit.calibratedAngleDeg == ageJustOver.calibratedAngleDeg && ...
    isequal(ageAtLimit.stageReached,ageJustOver.stageReached) && ...
    isequal(ageAtLimit.boundaryCrossed,ageJustOver.boundaryCrossed), ...
    'Age metadata may change quality but not value or path reachability.');

boundaryChoices = { ...
    'sensor-to-adc', ...
    'adc-to-calibration', ...
    'calibration-to-quality', ...
    'quality-to-controller'};
for k = 1:numel(boundaryChoices)
    stopped = model(30,12,5,20,boundaryChoices{k}, ...
        'none','complete');
    assertTraceInvariant(stopped);
    assert(stopped.firstOpenBoundary == k && ...
        stopped.deepestReachedStage == k && ...
        stopped.boundaryAttempted(k) && ~stopped.boundaryCrossed(k) && ...
        stopped.crossedBoundaryCount == k - 1 && ...
        ~stopped.endpointReceived && ~stopped.measurementUsable && ...
        ~stopped.reportedUsable && ~stopped.traceContractMet && ...
        strcmp(stopped.terminalStatus,'boundary-open') && ...
        strcmp(stopped.failureMode,boundaryChoices{k}), ...
        'Each open boundary must stop the trace at its source stage.');
end

cancelled = model(30,12,5,20,'none','cancellation','complete');
timedOut = model(30,12,5,20,'none','timeout','complete');
tied = model(30,12,5,20,'none', ...
    'cancellation-timeout-tie','complete');
eventBeforeBoundary = model(30,12,5,20,'sensor-to-adc', ...
    'timeout','complete');
for candidate = {cancelled,timedOut,tied,eventBeforeBoundary}
    assertTraceInvariant(candidate{1});
    assert(candidate{1}.eventObserved && ~candidate{1}.entryPermitted && ...
        ~any(candidate{1}.stageReached) && ...
        ~any(candidate{1}.boundaryAttempted) && ...
        ~any(candidate{1}.boundaryCrossed) && ...
        candidate{1}.deepestReachedStage == 0 && ...
        ~candidate{1}.qualityEvaluated && ...
        ~candidate{1}.freshnessCriterionMet && ...
        isnan(candidate{1}.freshnessMarginMs) && ...
        ~candidate{1}.endpointReceived && ...
        ~candidate{1}.measurementUsable && ...
        candidate{1}.terminalOutcomeHandled && candidate{1}.traceContractMet, ...
        'An acquisition-entry event must produce no sample or downstream state.');
end
assert(cancelled.cancellationObserved && ~cancelled.timeoutObserved && ...
    strcmp(cancelled.terminalStatus,'cancelled') && ...
    strcmp(cancelled.failureMode,'acquisition-cancelled'), ...
    'Cancellation must remain distinguishable from timeout.');
assert(~timedOut.cancellationObserved && timedOut.timeoutObserved && ...
    strcmp(timedOut.terminalStatus,'timed-out') && ...
    strcmp(timedOut.failureMode,'acquisition-timeout'), ...
    'Timeout must remain a pre-asserted guard, not measured timing.');
assert(tied.cancellationObserved && tied.timeoutObserved && ...
    tied.tieResolvedToCancellation && strcmp(tied.terminalStatus,'cancelled'), ...
    'Cancellation must retain inherited precedence in the injected tie.');
assert(eventBeforeBoundary.firstOpenBoundary == 0 && ...
    strcmp(eventBeforeBoundary.terminalStatus,'timed-out'), ...
    'An entry timeout must precede evaluation of a declared downstream opening.');

stale = model(30,12,21,20,'none','none','complete');
saturatedAndStale = model(181,12,21,20,'none','none','complete');
assertTraceInvariant(stale);
assertTraceInvariant(saturatedAndStale);
assert(stale.endpointReceived && stale.qualityEvaluated && ...
    ~stale.qualityValid && ~stale.measurementUsable && ...
    strcmp(stale.failureMode,'stale-sample'), ...
    'Stale data must remain received, invalid, and unusable.');
assert(saturatedAndStale.sensorSaturated && ...
    ~saturatedAndStale.freshnessCriterionMet && ...
    strcmp(saturatedAndStale.failureMode,'sensor-saturated-and-stale'), ...
    'Concurrent saturation and stale quality must remain distinguishable.');

brokenValueOnly = model(30,12,21,20,'none','none','value-only');
assertTraceInvariant(brokenValueOnly);
assert(isequal(stale.stageReached,brokenValueOnly.stageReached) && ...
    isequaln(stale.stageOutputValue,brokenValueOnly.stageOutputValue) && ...
    isequal(stale.boundaryAttempted,brokenValueOnly.boundaryAttempted) && ...
    isequal(stale.boundaryCrossed,brokenValueOnly.boundaryCrossed) && ...
    stale.qualityValid == brokenValueOnly.qualityValid && ...
    stale.measurementUsable == brokenValueOnly.measurementUsable && ...
    stale.traceContractMet == brokenValueOnly.traceContractMet && ...
    ~stale.reportedUsable && brokenValueOnly.reportedUsable && ...
    brokenValueOnly.falseUsable && ...
    strcmp(brokenValueOnly.reportingFailureMode, ...
    'value-only-false-usable'), ...
    'Value-only assessment may alter only reporting, never factual path or quality.');
saturatedValueOnly = model(181,12,5,20,'none','none','value-only');
saturatedAndStaleValueOnly = model(181,12,21,20, ...
    'none','none','value-only');
completeInvalidCases = {model(181,12,5,20,'none','none','complete'), ...
    saturatedAndStale};
brokenInvalidCases = {saturatedValueOnly,saturatedAndStaleValueOnly};
for k = 1:numel(completeInvalidCases)
    completeInvalid = completeInvalidCases{k};
    brokenInvalid = brokenInvalidCases{k};
    assertTraceInvariant(brokenInvalid);
    assert(isequal(completeInvalid.stageReached,brokenInvalid.stageReached) && ...
        isequaln(completeInvalid.stageOutputValue, ...
        brokenInvalid.stageOutputValue) && ...
        completeInvalid.qualityValid == brokenInvalid.qualityValid && ...
        completeInvalid.measurementUsable == ...
        brokenInvalid.measurementUsable && ...
        completeInvalid.p06InputEligible == brokenInvalid.p06InputEligible && ...
        isnan(completeInvalid.p06ObservedAngleDeg) && ...
        isnan(brokenInvalid.p06ObservedAngleDeg) && ...
        ~completeInvalid.reportedUsable && brokenInvalid.reportedUsable && ...
        brokenInvalid.falseUsable, ...
        'Value-only reporting must not bypass saturation or the P06 eligibility gate.');
end
baselineValueOnly = model(30,12,5,20,'none','none','value-only');
assert(baselineValueOnly.reportedUsable && ...
    baselineValueOnly.measurementUsable && ~baselineValueOnly.falseUsable, ...
    'Value-only evidence is not false when complete quality is independently valid.');
missingValueOnly = model(30,12,21,20,'quality-to-controller', ...
    'none','value-only');
assertTraceInvariant(missingValueOnly);
assert(missingValueOnly.qualityEvaluated && ~missingValueOnly.qualityValid && ...
    ~missingValueOnly.endpointReceived && ~missingValueOnly.reportedUsable && ...
    ~missingValueOnly.falseUsable && ...
    strcmp(missingValueOnly.terminalStatus,'boundary-open'), ...
    'Value-only assessment must not turn a missing endpoint value into success.');

compatible = model(int16(30),uint8(12),single(5),uint16(20), ...
    string(' NONE '),string('NONE'),string(' COMPLETE '));
assert(isequaln(compatible,baseline), ...
    'Compatible numeric scalar and scalar-text classes must normalize identically.');

expectErrorId(@() model(NaN,12,5,20,'none','none','complete'), ...
    'P07:InvalidAngle');
expectAnyError(@() model(Inf,12,5,20,'none','none','complete'));
expectAnyError(@() model(1+1i,12,5,20,'none','none','complete'));
expectAnyError(@() model([30 31],12,5,20,'none','none','complete'));
expectAnyError(@() model('30',12,5,20,'none','none','complete'));
expectAnyError(@() model(360.001,12,5,20,'none','none','complete'));
expectAnyError(@() model(-360.001,12,5,20,'none','none','complete'));
expectErrorId(@() model(30,3,5,20,'none','none','complete'), ...
    'P07:InvalidAdcBits');
expectAnyError(@() model(30,17,5,20,'none','none','complete'));
expectAnyError(@() model(30,12.5,5,20,'none','none','complete'));
expectAnyError(@() model(30,[10 12],5,20,'none','none','complete'));
expectAnyError(@() model(30,'12',5,20,'none','none','complete'));
expectErrorId(@() model(30,12,-0.001,20,'none','none','complete'), ...
    'P07:InvalidSampleAge');
expectAnyError(@() model(30,12,10000.001,20,'none','none','complete'));
expectAnyError(@() model(30,12,NaN,20,'none','none','complete'));
expectAnyError(@() model(30,12,[5 6],20,'none','none','complete'));
expectErrorId(@() model(30,12,5,-0.001,'none','none','complete'), ...
    'P07:InvalidFreshnessLimit');
expectAnyError(@() model(30,12,5,10000.001,'none','none','complete'));
expectAnyError(@() model(30,12,5,Inf,'none','none','complete'));
expectAnyError(@() model(30,12,5,[20 21],'none','none','complete'));
expectErrorId(@() model(30,12,5,20,'missing-boundary','none', ...
    'complete'),'P07:InvalidBoundary');
expectErrorId(@() model(30,12,5,20,'none','deadline', ...
    'complete'),'P07:InvalidEventMode');
expectErrorId(@() model(30,12,5,20,'none','none', ...
    'quality-only'),'P07:InvalidAssessmentMode');
expectAnyError(@() model(30,12,5,20, ...
    string({'none','sensor-to-adc'}),'none','complete'));
expectAnyError(@() model(30,12,5,20,1,'none','complete'));

afterMalformed = model(30,12,5,20,'none','none','complete');
afterSaturated = model(30,12,5,20,'none','none','complete');
afterStale = model(30,12,5,20,'none','none','complete');
afterBoundary = model(30,12,5,20,'none','none','complete');
afterCancellation = model(30,12,5,20,'none','none','complete');
afterTimeout = model(30,12,5,20,'none','none','complete');
afterBroken = model(30,12,5,20,'none','none','complete');
assert(isequaln(afterMalformed,baseline) && ...
    isequaln(afterSaturated,baseline) && isequaln(afterStale,baseline) && ...
    isequaln(afterBoundary,baseline) && ...
    isequaln(afterCancellation,baseline) && ...
    isequaln(afterTimeout,baseline) && isequaln(afterBroken,baseline), ...
    'Valid calls after malformed, invalid, missing, guarded, or broken calls must recover exactly.');
disp('P07 checks passed: values, quality, boundaries, guards, limits, recovery, and isolation.');
end

function assertTraceInvariant(out)
assert(out.stageCount == 5 && out.boundaryCount == 4 && ...
    isequal(size(out.stageReached),[1 5]) && ...
    isequal(size(out.stageOutputValue),[1 5]) && ...
    isequal(size(out.boundaryAttempted),[1 4]) && ...
    isequal(size(out.boundaryCrossed),[1 4]) && ...
    isequal(size(out.boundaryOpen),[1 4]), ...
    'Every trace must stay inside the fixed resource envelope.');
assert(out.stageReached(1) == out.entryPermitted && ...
    isequal(out.stageReached(2:end),out.boundaryCrossed) && ...
    all(~out.boundaryCrossed | out.boundaryAttempted) && ...
    all(diff(double(out.stageReached)) <= 0), ...
    'Stage reachability must be an empty or contiguous prefix.');
assert(all(isfinite(out.stageOutputValue(out.stageReached))) && ...
    all(isnan(out.stageOutputValue(~out.stageReached))), ...
    'Reached stages need finite payloads and unreachable stages need no value.');
assert(out.deepestReachedStage == sum(out.stageReached) && ...
    out.crossedBoundaryCount == sum(out.boundaryCrossed), ...
    'Trace summary indices must derive from the visible Boolean arrays.');
if out.firstOpenBoundary > 0
    assert(out.boundaryAttempted(out.firstOpenBoundary) && ...
        out.boundaryOpen(out.firstOpenBoundary) && ...
        ~out.boundaryCrossed(out.firstOpenBoundary), ...
        'The first open boundary must be evaluated but not crossed.');
end
if out.stageReached(2)
    assert(out.adcCount == round(out.adcCount) && out.adcCount >= 0 && ...
        out.adcCount <= out.maxAdcCount, ...
        'A reached ADC stage must carry one bounded integer count.');
end
if out.stageReached(3)
    assert(isfinite(out.calibratedAngleDeg) && ...
        abs(out.quantizationErrorDeg) <= out.quantizationBoundDeg + 1e-12, ...
        'A calibrated sample must satisfy the declared half-LSB bound.');
end
assert(out.qualityEvaluated == out.stageReached(4) && ...
    out.measurementUsable == (out.endpointReceived && out.qualityValid), ...
    'Quality evaluation and factual usability must follow reachability.');
if out.qualityEvaluated
    assert(isfinite(out.freshnessMarginMs), ...
        'A reached qualification stage must evaluate freshness.');
else
    assert(~out.freshnessCriterionMet && isnan(out.freshnessMarginMs), ...
        'An unreached qualification stage must not report a freshness result.');
end
assert(out.p06InputEligible == out.measurementUsable && ...
    out.p06ScalarAdapterMet && ...
    ((out.p06InputEligible && isfinite(out.p06ObservedAngleDeg) && ...
    abs(out.p06ObservedAngleDeg) <= out.sensorFullScaleAngleDeg && ...
    out.p06ObservedAngleDeg == out.stageOutputValue(5)) || ...
    (~out.p06InputEligible && isnan(out.p06ObservedAngleDeg))), ...
    'P07 must gate the unchanged scalar P06 input without adding validity to it.');
if out.endpointReceived
    assert(out.stageReached(5) && out.payloadPreservedToEndpoint && ...
        out.qualityFlagPreservedToEndpoint && ...
        out.stageOutputValue(5) == out.stageOutputValue(4), ...
        'Endpoint receipt must preserve both value and quality.');
end
if out.eventObserved
    assert(~any(out.stageReached) && out.terminalOutcomeHandled && ...
        out.traceContractMet, ...
        'A handled acquisition-entry guard must create no sample.');
end
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
