function run_checks
%RUN_CHECKS Independent P04 invariants, limits, and functional failures.
baseline = model(30,0.35,3,45,0.5,1000,Inf,'complete');
repeat = model(30,0.35,3,45,0.5,1000,Inf,'complete');
assert(isequaln(baseline,repeat), ...
    'Repeated baseline calls must be deterministic and stateless.');
assert(baseline.sampleTimeMs == 20 && baseline.horizonMs == 3000 && ...
    baseline.sampleCount == 151 && baseline.functionCount == 10, ...
    'The fixed functional resource envelope changed unexpectedly.');
assert(isequal(size(baseline.functionActivation),[151 10]) && ...
    numel(baseline.functionInputs) == 10 && ...
    numel(baseline.functionOutputs) == 10 && ...
    numel(baseline.functionFailureModes) == 10, ...
    'Every named function must retain a fixed activation and contract record.');
assert(baseline.executedFunctionCount == 10 && ...
    all(any(baseline.functionActivation,1)), ...
    'The complete baseline must exercise every required function.');

expectedFirstEntryMs = ceil(log(0.5/30)/log(1 - 0.35))*20;
expectedReportMs = expectedFirstEntryMs + (3 - 1)*20;
expectedPositionAtReportDeg = 30*(1 - (1 - 0.35)^12);
assert(expectedFirstEntryMs == 200 && expectedReportMs == 240, ...
    'The independent geometric-error timing calculation changed unexpectedly.');
assert(baseline.firstWithinRequestToleranceMs == expectedFirstEntryMs && ...
    baseline.reportTimeMs == expectedReportMs && ...
    abs(baseline.positionAtReportDeg - expectedPositionAtReportDeg) < 1e-12, ...
    'Baseline observables must agree with the independent geometric-error law.');
assert(strcmp(baseline.status,'completed') && baseline.reportedSuccess && ...
    baseline.requirementsMet && ~baseline.falseSuccess && ...
    strcmp(baseline.failureMode,'none'), ...
    'The valid complete decomposition must report trustworthy success.');

slowResponse = model(30,0.20,3,45,0.5,1000,Inf,'complete');
fastResponse = model(30,0.70,3,45,0.5,1000,Inf,'complete');
assert(slowResponse.reportTimeMs == 420 && fastResponse.reportTimeMs == 120 && ...
    fastResponse.firstWithinRequestToleranceMs < ...
    slowResponse.firstWithinRequestToleranceMs, ...
    'Response fraction must change convergence through the correction function.');
unityResponse = model(30,1,3,45,0.5,1000,Inf,'complete');
assert(unityResponse.positionDeg(2) == 30 && unityResponse.reportTimeMs == 60 && ...
    unityResponse.requestErrorAtReportDeg == 0, ...
    'A unity response fraction must remove all local error in one update.');
zeroResponse = model(30,0,3,45,0.5,100,Inf,'complete');
assert(strcmp(zeroResponse.status,'deadline-missed') && ...
    ~zeroResponse.physicalMotionOccurred && all(zeroResponse.positionDeg == 0) && ...
    zeroResponse.safeHoldRequired, ...
    'A zero response fraction must time out and require safe hold without motion.');

oneConfirmation = model(30,0.35,1,45,0.5,1000,Inf,'complete');
eightConfirmations = model(30,0.35,8,45,0.5,1000,Inf,'complete');
assert(oneConfirmation.firstWithinRequestToleranceMs == ...
    eightConfirmations.firstWithinRequestToleranceMs && ...
    oneConfirmation.reportTimeMs == 200 && eightConfirmations.reportTimeMs == 340, ...
    'Confirmation depth must delay evidence without moving first physical entry.');
assert(eightConfirmations.reportTimeMs - oneConfirmation.reportTimeMs == 7*20, ...
    'Each added consecutive observation must add exactly one update interval.');
depthPastDeadline = model(30,0.35,8,45,0.5,220,Inf,'complete');
assert(depthPastDeadline.firstWithinRequestToleranceMs == 200 && ...
    strcmp(depthPastDeadline.status,'deadline-missed') && ...
    ~depthPastDeadline.reportedSuccess, ...
    'Evidence depth that cannot finish by the deadline must report a timeout.');

zeroRequest = model(0,0.35,3,45,0.5,1000,Inf,'complete');
assert(~zeroRequest.physicalMotionOccurred && all(zeroRequest.positionDeg == 0) && ...
    zeroRequest.firstWithinRequestToleranceMs == 0 && ...
    zeroRequest.reportTimeMs == 40 && zeroRequest.requirementsMet, ...
    'Zero requested motion must need evidence but no physical correction.');
negativeRequest = model(-30,0.35,3,45,0.5,1000,Inf,'complete');
assert(max(abs(negativeRequest.positionDeg + baseline.positionDeg)) < 1e-12 && ...
    max(abs(negativeRequest.correctionDeg + baseline.correctionDeg)) < 1e-12 && ...
    negativeRequest.reportTimeMs == baseline.reportTimeMs && ...
    negativeRequest.requirementsMet, ...
    'A negative request must be the signed mirror of the positive chain.');
exactAuthority = model(45,0.35,3,45,0.5,1000,Inf,'complete');
assert(exactAuthority.authorityValid && exactAuthority.requirementsMet && ...
    exactAuthority.effectiveTargetDeg == 45, ...
    'A request exactly at declared authority must remain valid.');
justOutsideAuthority = model(45.0001,0.35,3,45,0.5,1000,Inf,'complete');
assert(strcmp(justOutsideAuthority.status,'rejected') && ...
    ~justOutsideAuthority.authorityValid && ~justOutsideAuthority.physicalMotionOccurred, ...
    'A request just outside declared authority must be rejected without motion.');

rejectedRequest = model(70,0.35,3,45,0.5,1000,Inf,'complete');
assert(strcmp(rejectedRequest.status,'rejected') && ...
    strcmp(rejectedRequest.failureMode,'request-rejected') && ...
    rejectedRequest.reportTimeMs == 0 && ~rejectedRequest.physicalMotionOccurred && ...
    ~rejectedRequest.reportedSuccess && ~rejectedRequest.requirementsMet, ...
    'Complete validation must reject an out-of-authority request before motion.');
brokenIntent = model(70,0.35,3,45,0.5,1000,Inf,'bypass-validation');
assert(brokenIntent.effectiveTargetDeg == 45 && ...
    brokenIntent.monitorTargetDeg == 45 && brokenIntent.reportedSuccess && ...
    brokenIntent.falseSuccess && ~brokenIntent.requirementsMet, ...
    'The broken architecture must expose local success with unmet original intent.');
assert(strcmp(brokenIntent.failureMode,'intent-lost') && ...
    brokenIntent.requestErrorAtReportDeg > 25 && ...
    brokenIntent.monitorErrorAtReportDeg < 0.5 && ...
    ~any(brokenIntent.functionActivation(:,2)) && ...
    brokenIntent.executedFunctionCount == 9 && ...
    strcmp(brokenIntent.architecturallyOmittedFunctionNames{1},'Validate authority'), ...
    'Missing validation must remain visible in both error signals and activation.');

deadlineMiss = model(30,0.35,3,45,0.5,100,Inf,'complete');
assert(strcmp(deadlineMiss.status,'deadline-missed') && ...
    strcmp(deadlineMiss.failureMode,'deadline-missed') && ...
    deadlineMiss.reportTimeMs == 100 && deadlineMiss.physicalMotionOccurred && ...
    ~deadlineMiss.reportedSuccess && ~deadlineMiss.requirementsMet, ...
    'A short deadline must terminate partial motion without reporting late success.');
assert(all(deadlineMiss.positionDeg(deadlineMiss.terminalSampleIndex:end) == ...
    deadlineMiss.positionAtReportDeg) && ...
    all(deadlineMiss.correctionDeg(deadlineMiss.terminalSampleIndex:end) == 0), ...
    'The bounded trace must terminate without further correction after timeout.');
deadlineTie = model(30,0.35,3,45,0.5,240,Inf,'complete');
oneUpdateEarly = model(30,0.35,3,45,0.5,220,Inf,'complete');
assert(deadlineTie.requirementsMet && strcmp(deadlineTie.status,'completed') && ...
    strcmp(oneUpdateEarly.status,'deadline-missed') && ...
    ~oneUpdateEarly.requirementsMet, ...
    'Completion exactly at the deadline must pass; one update earlier must fail.');

cancelBeforeMotion = model(30,0.35,3,45,0.5,1000,0,'complete');
cancelDuringMotion = model(30,0.35,3,45,0.5,1000,120,'complete');
cancelCompletionTie = model(30,0.35,3,45,0.5,1000,240,'complete');
cancelDeadlineTie = model(30,0.35,3,45,0.5,100,100,'complete');
cancelAfterCompletion = model(30,0.35,3,45,0.5,1000,260,'complete');
assert(strcmp(cancelBeforeMotion.status,'cancelled') && ...
    ~cancelBeforeMotion.physicalMotionOccurred && cancelBeforeMotion.reportTimeMs == 0, ...
    'Cancellation at receipt must prevent physical motion.');
assert(strcmp(cancelDuringMotion.status,'cancelled') && ...
    cancelDuringMotion.physicalMotionOccurred && ...
    cancelDuringMotion.positionAtReportDeg > 27 && ...
    ~cancelDuringMotion.reportedSuccess, ...
    'Cancellation during motion must report a distinct stopped terminal state.');
assert(all(cancelDuringMotion.positionDeg(cancelDuringMotion.terminalSampleIndex:end) == ...
    cancelDuringMotion.positionAtReportDeg) && ...
    all(cancelDuringMotion.correctionDeg(cancelDuringMotion.terminalSampleIndex:end) == 0), ...
    'The bounded trace must terminate without further correction after cancellation.');
assert(strcmp(cancelCompletionTie.status,'cancelled') && ...
    ~cancelCompletionTie.reportedSuccess && ...
    cancelCompletionTie.requestSatisfiedAtReport, ...
    'Cancellation must have safety priority when tied with completion.');
assert(strcmp(cancelDeadlineTie.status,'cancelled') && ...
    strcmp(cancelDeadlineTie.failureMode,'cancelled') && ...
    cancelDeadlineTie.reportTimeMs == 100 && ...
    cancelDeadlineTie.cancellationObserved && cancelDeadlineTie.safeHoldRequired && ...
    ~cancelDeadlineTie.reportedSuccess, ...
    'Cancellation must have safety priority when tied with the deadline.');
assert(strcmp(cancelAfterCompletion.status,'completed') && ...
    cancelAfterCompletion.requirementsMet && ...
    cancelAfterCompletion.cancellationRequested && ...
    ~cancelAfterCompletion.cancellationObserved, ...
    'A cancellation after terminal completion must not rewrite the retained result.');
assert(all(baseline.positionDeg(baseline.terminalSampleIndex:end) == ...
    baseline.positionAtReportDeg) && ...
    all(baseline.correctionDeg(baseline.terminalSampleIndex:end) == 0), ...
    'The bounded trace must terminate without further correction after completion.');

maxBounded = model(180,1,20,180,30,3000,Inf,'complete');
assert(maxBounded.sampleCount == 151 && maxBounded.functionCount == 10 && ...
    maxBounded.requirementsMet && maxBounded.reportTimeMs == 400, ...
    'Maximum accepted scalar bounds must retain fixed resources and complete.');

compatible = model(int16(30),single(0.5),uint8(3),uint16(45), ...
    single(0.5),uint16(1000),single(Inf),string('complete'));
compatibleReference = model(30,0.5,3,45,0.5,1000,Inf,'complete');
assert(isequaln(compatible,compatibleReference), ...
    'Compatible numeric scalar and scalar-text classes must normalize identically.');

expectAnyError(@() model(NaN,0.35,3,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(Inf,0.35,3,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(1+1i,0.35,3,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model([20 30],0.35,3,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(30,-0.1,3,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(30,1.1,3,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(30,0.35,0,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(30,0.35,2.5,45,0.5,1000,Inf,'complete'));
expectAnyError(@() model(30,0.35,3,0,0.5,1000,Inf,'complete'));
expectAnyError(@() model(30,0.35,3,45,0,1000,Inf,'complete'));
expectAnyError(@() model(30,0.35,3,45,0.5,0,Inf,'complete'));
expectErrorId(@() model(30,0.35,3,0.25,0.5,1000,Inf,'complete'), ...
    'P04:InvalidTolerance');
expectErrorId(@() model(30,0.35,3,45,0.5,999,Inf,'complete'), ...
    'P04:InvalidDeadlineGrid');
expectErrorId(@() model(30,0.35,3,45,0.5,1000,-1,'complete'), ...
    'P04:InvalidCancelTime');
expectErrorId(@() model(30,0.35,3,45,0.5,1000,1,'complete'), ...
    'P04:InvalidCancelTime');
expectErrorId(@() model(30,0.35,3,45,0.5,1000,NaN,'complete'), ...
    'P04:InvalidCancelTime');
expectErrorId(@() model(30,0.35,3,45,0.5,1000,-Inf,'complete'), ...
    'P04:InvalidCancelTime');
expectErrorId(@() model(30,0.35,3,45,0.5,1000,Inf,'unknown'), ...
    'P04:InvalidArchitecture');
expectErrorId(@() model(181,0.35,3,45,0.5,1000,Inf,'complete'), ...
    'P04:ResourceBound');
expectErrorId(@() model(30,0.35,3,181,0.5,1000,Inf,'complete'), ...
    'P04:ResourceBound');
expectErrorId(@() model(30,0.35,3,45,31,1000,Inf,'complete'), ...
    'P04:ResourceBound');
expectErrorId(@() model(30,0.35,21,45,0.5,1000,Inf,'complete'), ...
    'P04:ResourceBound');
expectErrorId(@() model(30,0.35,3,45,0.5,3020,Inf,'complete'), ...
    'P04:ResourceBound');
expectErrorId(@() model(30,0.35,3,45,0.5,1000,3020,'complete'), ...
    'P04:ResourceBound');

afterFailure = model(30,0.35,3,45,0.5,1000,Inf,'complete');
assert(isequaln(afterFailure,baseline), ...
    'A valid call after malformed and failure cases must recover without hidden state.');
afterIsolationProbe = model(30,0.35,3,45,0.5,1000,Inf,'complete');
assert(isequaln(afterIsolationProbe,baseline), ...
    'Independent calls must remain isolated from prior broken, timeout, and cancel paths.');
disp('P04 checks passed: functions, levers, limits, terminals, recovery, and bounds.');
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
