function run_checks()
%RUN_CHECKS Independent timing equations, events, limits, and recovery.

tolerance = 1e-12;
expectedStageNames = {'Input acquisition','Command calculation', ...
    'Command transport','Apply and observe'};
expectedNominalStageMs = [0.6 0.5 1.2 1.0];
expectedBaseAllocationMs = [0.1 0.1 0.3 0.2];
expectedPattern = [ ...
     0  0  0  0; ...
     1 -1  0  1; ...
    -1  1  1  0; ...
     1  1  1  1; ...
     0 -1 -1  1; ...
    -1  0  1 -1; ...
     1  0 -1  0; ...
    -1 -1 -1 -1; ...
     0  1  0 -1; ...
     1 -1  1 -1; ...
    -1  1 -1  1; ...
     0  0  0  0];
expectedStageVariationMs = expectedPattern .* ...
    expectedBaseAllocationMs;
expectedStageLatencyMs = expectedNominalStageMs + ...
    expectedStageVariationMs;
expectedLatencyMs = sum(expectedStageLatencyMs,2)';
expectedReleaseMs = (0:11) .* 6.0;
expectedDeadlineMs = expectedReleaseMs + 4.2;
expectedCompletionMs = expectedReleaseMs + expectedLatencyMs;

baseline = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
assertTimingInvariant(baseline);
assert(isequal(baseline.stageNames,expectedStageNames) && ...
    max(abs(baseline.nominalStageLatencyMs - ...
    expectedNominalStageMs)) < tolerance && ...
    max(abs(baseline.baseJitterAllocationMs - ...
    expectedBaseAllocationMs)) < tolerance && ...
    isequal(baseline.jitterPattern,expectedPattern), ...
    'The fixed P11 stage or pattern identity changed.');
assert(all(sum(expectedPattern,1) == 0) && ...
    all(expectedPattern(4,:) == 1) && ...
    all(expectedPattern(8,:) == -1) && ...
    max(abs(baseline.plannedStageVariationMs(:) - ...
    expectedStageVariationMs(:))) < tolerance && ...
    max(abs(baseline.plannedStageLatencyMs(:) - ...
    expectedStageLatencyMs(:))) < tolerance, ...
    'Pattern balance or stage recurrence changed.');
assert(max(abs(expectedLatencyMs - ...
    [3.3 3.5 3.6 4.0 3.1 3.3 3.1 2.6 3.2 3.4 3.2 3.3])) < ...
    tolerance && ...
    max(abs(baseline.plannedLatencyMs - expectedLatencyMs)) < ...
    tolerance && ...
    max(abs(baseline.plannedReleaseMs - expectedReleaseMs)) < ...
    tolerance && ...
    max(abs(baseline.plannedDeadlineMs - expectedDeadlineMs)) < ...
    tolerance && ...
    max(abs(baseline.plannedCompletionMs - expectedCompletionMs)) < ...
    tolerance, ...
    'The independent baseline time trace changed.');
assert(abs(baseline.nominalLatencyMs - 3.3) < tolerance && ...
    abs(baseline.strictJitterAllowanceMs - 0.7) < tolerance && ...
    abs(baseline.strictLowerBoundMs - 2.6) < tolerance && ...
    abs(baseline.strictUpperBoundMs - 4.0) < tolerance && ...
    abs(baseline.strictPeakToPeakJitterMs - 1.4) < tolerance && ...
    abs(mean(baseline.plannedLatencyMs) - 3.3) < tolerance && ...
    abs(baseline.strictMarginMs - 0.2) < tolerance && ...
    baseline.strictBudgetAccepted && ...
    baseline.reportedBudgetAccepted && ...
    baseline.assessmentDecisionCorrect && ~baseline.falseApproval && ...
    all(baseline.cycleStarted) && all(baseline.cycleCompleted) && ...
    baseline.scheduleCompleted && ~baseline.eventObserved && ...
    strcmp(baseline.terminalStatus,'completed-within-budget') && ...
    strcmp(baseline.failureMode,'none'), ...
    'Baseline bounds, acceptance, or terminal changed.');

transportSweepMs = [0.6 1.2 1.8 2.4];
expectedTransportUpperMs = [3.4 4.0 4.6 5.2];
expectedTransportMarginMs = [0.8 0.2 -0.4 -1.0];
observedTransportUpperMs = zeros(size(transportSweepMs));
observedTransportMarginMs = zeros(size(transportSweepMs));
for k = 1:numel(transportSweepMs)
    trial = model(transportSweepMs(k),1.0,4.2,true,Inf, ...
        'bounded-sum');
    assertTimingInvariant(trial);
    observedTransportUpperMs(k) = trial.strictUpperBoundMs;
    observedTransportMarginMs(k) = trial.strictMarginMs;
    assert(trial.inputs.jitterScale == 1.0 && ...
        trial.inputs.deadlineMs == 4.2 && ...
        abs(trial.strictPeakToPeakJitterMs - 1.4) < tolerance, ...
        'Transport sweep must isolate nominal transport latency.');
end
assert(max(abs(observedTransportUpperMs - ...
    expectedTransportUpperMs)) < tolerance && ...
    max(abs(observedTransportMarginMs - ...
    expectedTransportMarginMs)) < tolerance, ...
    'Transport sweep or limiting cases changed.');

jitterScaleSweep = [0 0.5 1.0 1.5 2.0];
expectedJitterUpperMs = [3.3 3.65 4.0 4.35 4.7];
expectedJitterMarginMs = [0.9 0.55 0.2 -0.15 -0.5];
expectedPeakToPeakMs = [0 0.7 1.4 2.1 2.8];
observedJitterUpperMs = zeros(size(jitterScaleSweep));
observedJitterMarginMs = zeros(size(jitterScaleSweep));
observedPeakToPeakMs = zeros(size(jitterScaleSweep));
for k = 1:numel(jitterScaleSweep)
    trial = model(1.2,jitterScaleSweep(k),4.2,true,Inf, ...
        'bounded-sum');
    assertTimingInvariant(trial);
    observedJitterUpperMs(k) = trial.strictUpperBoundMs;
    observedJitterMarginMs(k) = trial.strictMarginMs;
    observedPeakToPeakMs(k) = trial.strictPeakToPeakJitterMs;
    assert(trial.inputs.transportNominalMs == 1.2 && ...
        abs(trial.nominalLatencyMs - 3.3) < tolerance, ...
        'Jitter sweep must isolate bounded variation.');
end
assert(max(abs(observedJitterUpperMs - expectedJitterUpperMs)) < ...
    tolerance && ...
    max(abs(observedJitterMarginMs - expectedJitterMarginMs)) < ...
    tolerance && ...
    max(abs(observedPeakToPeakMs - expectedPeakToPeakMs)) < ...
    tolerance, ...
    'Jitter sweep or limiting cases changed.');

zeroJitter = model(1.2,0,3.3,true,Inf,'bounded-sum');
exactDeadline = model(1.2,1.0,4.0,true,Inf,'bounded-sum');
assertTimingInvariant(zeroJitter);
assertTimingInvariant(exactDeadline);
assert(all(abs(zeroJitter.plannedLatencyMs - 3.3) < tolerance) && ...
    zeroJitter.strictJitterAllowanceMs == 0 && ...
    zeroJitter.strictPeakToPeakJitterMs == 0 && ...
    zeroJitter.scheduleCompleted && zeroJitter.strictBudgetAccepted && ...
    exactDeadline.scheduleCompleted && ...
    exactDeadline.strictBudgetAccepted && ...
    ~exactDeadline.timeoutObserved && ...
    abs(exactDeadline.plannedLatencyMs(4) - ...
    exactDeadline.inputs.deadlineMs) < tolerance, ...
    'Zero-jitter or inclusive-deadline limit changed.');

blocked = model(1.2,1.0,4.2,false,Inf,'bounded-sum');
assertTimingInvariant(blocked);
assert(~any(blocked.cycleStarted) && ~any(blocked.cycleCompleted) && ...
    all(isnan(blocked.actualReleaseMs)) && ...
    all(isnan(blocked.actualLatencyMs)) && ...
    all(all(isnan(blocked.actualStageLatencyMs))) && ...
    all(isfinite(blocked.plannedLatencyMs)) && ...
    ~blocked.strictBudgetAccepted && ~blocked.reportedBudgetAccepted && ...
    ~blocked.safeHoldRequested && ~blocked.rollbackRequired && ...
    strcmp(blocked.terminalStatus,'blocked-p10-activation-proof') && ...
    strcmp(blocked.failureMode,'p10-activation-proof-unavailable'), ...
    'Missing P10 proof must retain only offline design evidence.');

cancelled = model(1.2,1.0,4.2,true,15.0,'bounded-sum');
cancelledBeforeStart = model(1.2,1.0,4.2,true,0,'bounded-sum');
cancelAfterSchedule = model(1.2,1.0,4.2,true,100,'bounded-sum');
completionTied = model(1.2,1.0,4.2,true,9.5,'bounded-sum');
for candidate = {cancelled,cancelledBeforeStart,cancelAfterSchedule, ...
        completionTied}
    assertTimingInvariant(candidate{1});
end
expectedCancelStarted = [true true true false false false ...
    false false false false false false];
expectedCancelCompleted = [true true false false false false ...
    false false false false false false];
assert(isequal(cancelled.cycleStarted,expectedCancelStarted) && ...
    isequal(cancelled.cycleCompleted,expectedCancelCompleted) && ...
    max(abs(cancelled.actualLatencyMs(1:2) - ...
    expectedLatencyMs(1:2))) < tolerance && ...
    all(isnan(cancelled.actualLatencyMs(3:end))) && ...
    cancelled.cancellationRequested && cancelled.cancellationObserved && ...
    ~cancelled.timeoutObserved && cancelled.interruptedCycle == 3 && ...
    abs(cancelled.terminalTimeMs - 15.0) < tolerance && ...
    cancelled.safeHoldRequested && cancelled.rollbackRequired && ...
    ~cancelled.rollbackEvidenceAvailable && ...
    strcmp(cancelled.rollbackAuthority,'P10') && ...
    strcmp(cancelled.handoffEvent,'cancellation') && ...
    strcmp(cancelled.terminalStatus,'cancelled-safe-hold-requested'), ...
    'Cancellation ordering or P10 handoff boundary changed.');
assert(~any(cancelledBeforeStart.cycleStarted) && ...
    cancelledBeforeStart.cancellationObserved && ...
    cancelledBeforeStart.interruptedCycle == 1 && ...
    cancelledBeforeStart.terminalTimeMs == 0 && ...
    cancelAfterSchedule.scheduleCompleted && ...
    ~cancelAfterSchedule.eventObserved && ...
    cancelAfterSchedule.cancellationRequested, ...
    'Cancellation release boundary or after-schedule limit changed.');
expectedCompletionTieStarted = [true true false false false false ...
    false false false false false false];
expectedCompletionTieCompleted = [true false false false false false ...
    false false false false false false];
assert(isequal(completionTied.cycleStarted, ...
    expectedCompletionTieStarted) && ...
    isequal(completionTied.cycleCompleted, ...
    expectedCompletionTieCompleted) && ...
    completionTied.cancellationObserved && ...
    ~completionTied.timeoutObserved && ...
    completionTied.interruptedCycle == 2 && ...
    abs(completionTied.terminalTimeMs - 9.5) < tolerance && ...
    all(isnan(completionTied.actualLatencyMs(2:end))), ...
    'Cancellation must win an exact tie with planned completion.');

timedOut = model(1.2,2.0,4.2,true,Inf,'bounded-sum');
tied = model(1.2,2.0,4.2,true,22.2,'bounded-sum');
neighborOffsetMs = 1e-9;
justBeforeTimeoutTie = model(1.2,2.0,4.2,true, ...
    22.2 - neighborOffsetMs,'bounded-sum');
justAfterTimeoutTie = model(1.2,2.0,4.2,true, ...
    22.2 + neighborOffsetMs,'bounded-sum');
assertTimingInvariant(timedOut);
assertTimingInvariant(tied);
assertTimingInvariant(justBeforeTimeoutTie);
assertTimingInvariant(justAfterTimeoutTie);
expectedTimeoutStarted = [true true true true false false ...
    false false false false false false];
expectedTimeoutCompleted = [true true true false false false ...
    false false false false false false];
assert(isequal(timedOut.cycleStarted,expectedTimeoutStarted) && ...
    isequal(timedOut.cycleCompleted,expectedTimeoutCompleted) && ...
    all(isfinite(timedOut.actualLatencyMs(1:3))) && ...
    all(isnan(timedOut.actualLatencyMs(4:end))) && ...
    ~timedOut.cancellationObserved && timedOut.timeoutObserved && ...
    timedOut.interruptedCycle == 4 && ...
    abs(timedOut.terminalTimeMs - 22.2) < tolerance && ...
    strcmp(timedOut.handoffEvent,'timeout') && ...
    strcmp(timedOut.failureMode,'deadline-timeout') && ...
    strcmp(timedOut.terminalStatus,'timed-out-safe-hold-requested'), ...
    'The first derived timeout or output masking changed.');
assert(isequal(tied.cycleStarted,expectedTimeoutStarted) && ...
    isequal(tied.cycleCompleted,expectedTimeoutCompleted) && ...
    tied.cancellationObserved && tied.timeoutObserved && ...
    tied.tieResolvedToCancellation && tied.interruptedCycle == 4 && ...
    abs(tied.terminalTimeMs - 22.2) < tolerance && ...
    strcmp(tied.handoffEvent,'cancellation-timeout-tie') && ...
    strcmp(tied.failureMode,'cycle-cancelled') && ...
    strcmp(tied.terminalStatus,'cancelled-on-timeout-tie'), ...
    'Cancellation must win the exact cancellation/timeout tie.');
assert(justBeforeTimeoutTie.cancellationObserved && ...
    ~justBeforeTimeoutTie.timeoutObserved && ...
    ~justBeforeTimeoutTie.tieResolvedToCancellation && ...
    abs(justBeforeTimeoutTie.terminalTimeMs - ...
    (22.2 - neighborOffsetMs)) < tolerance && ...
    strcmp(justBeforeTimeoutTie.handoffEvent,'cancellation') && ...
    strcmp(justBeforeTimeoutTie.terminalStatus, ...
    'cancelled-safe-hold-requested'), ...
    'A pre-deadline cancellation must not be classified as a timeout tie.');
assert(~justAfterTimeoutTie.cancellationObserved && ...
    justAfterTimeoutTie.timeoutObserved && ...
    ~justAfterTimeoutTie.tieResolvedToCancellation && ...
    abs(justAfterTimeoutTie.terminalTimeMs - 22.2) < tolerance && ...
    strcmp(justAfterTimeoutTie.handoffEvent,'timeout') && ...
    strcmp(justAfterTimeoutTie.terminalStatus, ...
    'timed-out-safe-hold-requested'), ...
    'A post-deadline cancellation must not replace the earlier timeout.');

strictCase = model(1.2,2.0,4.2,true,Inf,'bounded-sum');
broken = model(1.2,2.0,4.2,true,Inf,'rss-uncorrelated');
assertTimingInvariant(strictCase);
assertTimingInvariant(broken);
expectedBrokenLatencyMs = ...
    [3.3 3.7 3.9 4.7 2.9 3.3 2.9 1.9 3.1 3.5 3.1 3.3];
assert(max(abs(broken.plannedLatencyMs - ...
    expectedBrokenLatencyMs)) < tolerance && ...
    isequal(strictCase.jitterPattern,broken.jitterPattern) && ...
    isequaln(strictCase.plannedStageLatencyMs, ...
    broken.plannedStageLatencyMs) && ...
    isequaln(strictCase.actualLatencyMs,broken.actualLatencyMs) && ...
    abs(broken.strictUpperBoundMs - 4.7) < tolerance && ...
    abs(broken.rssJitterAllowanceMs - sqrt(0.6)) < tolerance && ...
    abs(broken.reportedUpperBoundMs - ...
    (3.3 + sqrt(0.6))) < tolerance && ...
    ~broken.strictBudgetPass && broken.reportedBudgetPass && ...
    ~broken.strictBudgetAccepted && broken.reportedBudgetAccepted && ...
    broken.falseApproval && ~broken.assessmentDecisionCorrect && ...
    strcmp(broken.reportingFailureMode, ...
    'rss-independence-false-approval'), ...
    'Broken RSS must change only assessment and expose false approval.');

expectErrorId(@() model([1.2 1.3],1,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidTransportNominal');
expectErrorId(@() model(NaN,1,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidTransportNominal');
expectErrorId(@() model(1.2 + 1i,1,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidTransportNominal');
expectErrorId(@() model(0.59,1,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidTransportNominal');
expectErrorId(@() model(2.41,1,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidTransportNominal');
expectErrorId(@() model(true,1,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidTransportNominal');
expectErrorId(@() model(1.2,-0.01,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidJitterScale');
expectErrorId(@() model(1.2,2.01,4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidJitterScale');
expectErrorId(@() model(1.2,[1 2],4.2,true,Inf, ...
    'bounded-sum'),'P11:InvalidJitterScale');
expectErrorId(@() model(1.2,1,0,true,Inf, ...
    'bounded-sum'),'P11:InvalidDeadline');
expectErrorId(@() model(1.2,1,10.1,true,Inf, ...
    'bounded-sum'),'P11:InvalidDeadline');
expectErrorId(@() model(1.2,1,Inf,true,Inf, ...
    'bounded-sum'),'P11:InvalidDeadline');
expectErrorId(@() model(1.2,1,4.2,2,Inf, ...
    'bounded-sum'),'P11:InvalidP10ActivationProof');
expectErrorId(@() model(1.2,1,4.2,[true false],Inf, ...
    'bounded-sum'),'P11:InvalidP10ActivationProof');
expectErrorId(@() model(1.2,1,4.2,true,-1, ...
    'bounded-sum'),'P11:InvalidCancellationTime');
expectErrorId(@() model(1.2,1,4.2,true,NaN, ...
    'bounded-sum'),'P11:InvalidCancellationTime');
expectErrorId(@() model(1.2,1,4.2,true,-Inf, ...
    'bounded-sum'),'P11:InvalidCancellationTime');
expectErrorId(@() model(1.2,1,4.2,true,[15 16], ...
    'bounded-sum'),'P11:InvalidCancellationTime');
expectErrorId(@() model(1.2,1,4.2,true,'15', ...
    'bounded-sum'),'P11:InvalidCancellationTime');
expectErrorId(@() model(1.2,1,4.2,true,Inf, ...
    'mean-only'),'P11:InvalidAssessmentMode');
expectErrorId(@() model(1.2,1,4.2,true,Inf, ...
    ["bounded-sum" "rss-uncorrelated"]), ...
    'P11:InvalidAssessmentMode');

normalizedText = model(1.2,1,4.2,1,Inf, ...
    string(' BOUNDED-SUM '));
assert(isequaln(normalizedText,baseline), ...
    'Supported logical and scalar-text normalization changed.');

afterMalformed = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
afterCancellation = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
afterTimeout = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
afterBlocked = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
afterBroken = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
assert(isequaln(afterMalformed,baseline) && ...
    isequaln(afterCancellation,baseline) && ...
    isequaln(afterTimeout,baseline) && ...
    isequaln(afterBlocked,baseline) && ...
    isequaln(afterBroken,baseline), ...
    'Failures and events must not contaminate a fresh baseline call.');
mutated = baseline;
mutated.plannedLatencyMs(1) = -999;
afterMutation = model(1.2,1.0,4.2,true,Inf,'bounded-sum');
assert(isequaln(afterMutation,baseline) && ...
    mutated.plannedLatencyMs(1) ~= afterMutation.plannedLatencyMs(1), ...
    'Returned data must not become hidden mutable model state.');

disp('P11 checks passed.');
end

function assertTimingInvariant(out)
tolerance = 1e-12;
expectedCumulativeMs = cumsum(out.plannedStageLatencyMs,2);
assert(out.cycleCount == 12 && out.stageCount == 4 && ...
    out.stageCellCount == 48 && out.cyclePeriodMs == 6.0 && ...
    isequal(size(out.jitterPattern),[12 4]) && ...
    isequal(size(out.plannedStageVariationMs),[12 4]) && ...
    isequal(size(out.plannedStageLatencyMs),[12 4]) && ...
    isequal(size(out.plannedStageCompletionMs),[12 4]) && ...
    isequal(size(out.actualStageLatencyMs),[12 4]) && ...
    isequal(size(out.actualStageCompletionMs),[12 4]), ...
    'The fixed 12-cycle by four-stage resource envelope changed.');
assert(out.minimumTransportNominalMs == 0.6 && ...
    out.maximumTransportNominalMs == 2.4 && ...
    out.minimumJitterScale == 0 && out.maximumJitterScale == 2 && ...
    out.minimumDeadlineMs == 0.5 && out.maximumDeadlineMs == 10, ...
    'One or more public input bounds changed.');
assert(all(isfinite(out.plannedLatencyMs)) && ...
    all(all(isfinite(out.plannedStageLatencyMs))) && ...
    all(all(out.plannedStageLatencyMs >= 0)) && ...
    all(ismember(out.jitterPattern(:),[-1 0 1])) && ...
    all(sum(out.jitterPattern,1) == 0) && ...
    ~any(out.plannedBoundViolation), ...
    'Planned fixed data must remain finite, nonnegative, balanced, and bounded.');
assert(max(abs(out.plannedLatencyMs - ...
    sum(out.plannedStageLatencyMs,2)')) < tolerance && ...
    max(abs(out.plannedStageCumulativeMs(:) - ...
    expectedCumulativeMs(:))) < tolerance && ...
    max(abs(out.plannedCompletionMs - ...
    (out.plannedReleaseMs + out.plannedLatencyMs))) < tolerance && ...
    max(abs(out.plannedDeadlineMs - ...
    (out.plannedReleaseMs + out.inputs.deadlineMs))) < tolerance, ...
    'Stage, cycle, completion, or deadline equations changed.');
assert(abs(out.nominalLatencyMs - ...
    sum(out.nominalStageLatencyMs)) < tolerance && ...
    abs(out.strictJitterAllowanceMs - ...
    sum(out.jitterAllocationMs)) < tolerance && ...
    abs(out.strictUpperBoundMs - ...
    (out.nominalLatencyMs + out.strictJitterAllowanceMs)) < ...
    tolerance && ...
    abs(out.strictLowerBoundMs - ...
    (out.nominalLatencyMs - out.strictJitterAllowanceMs)) < ...
    tolerance && ...
    abs(out.strictMarginMs - ...
    (out.inputs.deadlineMs - out.strictUpperBoundMs)) < tolerance, ...
    'Nominal, jitter, bound, or margin identity changed.');
assert(out.strictBudgetPass == ...
    (out.strictUpperBoundMs <= out.inputs.deadlineMs) && ...
    out.strictBudgetAccepted == ...
    (out.inputs.p10ActivationProof && out.strictBudgetPass) && ...
    out.reportedBudgetAccepted == ...
    (out.inputs.p10ActivationProof && out.reportedBudgetPass) && ...
    out.falseApproval == ...
    (out.reportedBudgetAccepted && ~out.strictBudgetAccepted) && ...
    out.assessmentDecisionCorrect == ...
    (out.strictBudgetAccepted == out.reportedBudgetAccepted), ...
    'Strict and reported assessment truth changed.');
if strcmp(out.inputs.assessmentMode,'bounded-sum')
    assert(abs(out.reportedUpperBoundMs - ...
        out.strictUpperBoundMs) < tolerance, ...
        'Bounded-sum reporting must equal strict truth.');
else
    assert(abs(out.reportedUpperBoundMs - ...
        (out.nominalLatencyMs + sqrt(sum(out.jitterAllocationMs .^ 2)))) < ...
        tolerance, ...
        'RSS reporting equation changed.');
end
assert(all(isfinite(out.actualReleaseMs(out.cycleStarted))) && ...
    all(isnan(out.actualReleaseMs(~out.cycleStarted))) && ...
    isequaln(out.actualReleaseMs(out.cycleStarted), ...
    out.plannedReleaseMs(out.cycleStarted)) && ...
    all(isfinite(out.actualLatencyMs(out.cycleCompleted))) && ...
    all(isnan(out.actualLatencyMs(~out.cycleCompleted))) && ...
    isequaln(out.actualLatencyMs(out.cycleCompleted), ...
    out.plannedLatencyMs(out.cycleCompleted)) && ...
    all(isfinite(out.actualCompletionMs(out.cycleCompleted))) && ...
    all(isnan(out.actualCompletionMs(~out.cycleCompleted))) && ...
    isequaln(out.actualCompletionMs(out.cycleCompleted), ...
    out.plannedCompletionMs(out.cycleCompleted)) && ...
    all(all(isfinite(out.actualStageLatencyMs(out.cycleCompleted,:)))) && ...
    all(all(isnan(out.actualStageLatencyMs(~out.cycleCompleted,:)))) && ...
    isequaln(out.actualStageLatencyMs(out.cycleCompleted,:), ...
    out.plannedStageLatencyMs(out.cycleCompleted,:)) && ...
    all(all(isfinite(out.actualStageCompletionMs( ...
    out.cycleCompleted,:)))) && ...
    all(all(isnan(out.actualStageCompletionMs( ...
    ~out.cycleCompleted,:)))) && ...
    isequaln(out.actualStageCompletionMs(out.cycleCompleted,:), ...
    out.plannedStageCompletionMs(out.cycleCompleted,:)) && ...
    all(out.cycleCompleted <= out.cycleStarted) && ...
    out.completedCycleCount == sum(out.cycleCompleted) && ...
    out.scheduleCompleted == all(out.cycleCompleted), ...
    'Started, completed, and unavailable evidence masks changed.');
assert(out.eventObserved == ...
    (out.cancellationObserved || out.timeoutObserved) && ...
    out.safeHoldRequested == out.eventObserved && ...
    out.rollbackRequired == out.safeHoldRequested && ...
    ~out.rollbackEvidenceAvailable && ...
    strcmp(out.rollbackAuthority,'P10') && ...
    out.terminalOutcomeHandled, ...
    'Event handoff and rollback authority boundary changed.');
end

function expectErrorId(operation,expectedId)
observedId = '';
try
    operation();
catch caught
    observedId = caught.identifier;
end
assert(strcmp(observedId,expectedId), ...
    'Expected error %s but observed %s.',expectedId,observedId);
end
