function run_checks
%RUN_CHECKS Independent P03 invariants, limits, and failure cases.
baseline = model(30,1.5,0.7,45,0.5,2,1200);
repeat = model(30,1.5,0.7,45,0.5,2,1200);
assert(isequaln(baseline,repeat), ...
    'Repeated baseline calls must be deterministic and stateless.');
assert(baseline.sampleTimeMs == 2 && baseline.horizonMs == 10000 && ...
    baseline.maxDeadlineMs == 3000 && baseline.sampleCount == 5001, ...
    'The fixed response resource envelope changed unexpectedly.');
assert(baseline.timeMs(1) == 0 && baseline.timeMs(end) == 10000, ...
    'The response time base must cover the declared horizon exactly.');
assert(baseline.requestedCommandDeg == 30 && baseline.effectiveCommandDeg == 30 && ...
    ~baseline.commandWasLimited, ...
    'The valid baseline command must pass through command authority unchanged.');

expectedOvershootPercent = 100*exp(-pi*0.7/sqrt(1 - 0.7^2));
assert(abs(baseline.overshootPercent - expectedOvershootPercent) < 0.02, ...
    'Sampled overshoot must agree with the independent analytic value.');
assert(baseline.peakPositionMagnitudeDeg > 31 && ...
    baseline.peakPositionMagnitudeDeg < 32, ...
    'Baseline peak position left its independently bounded interval.');
assert(baseline.peakVelocityMagnitudeDegPerSec > 129 && ...
    baseline.peakVelocityMagnitudeDegPerSec < 131, ...
    'Baseline peak velocity left its independently bounded interval.');
assert(baseline.settlingTimeMs == 780 && baseline.settledByDeadline && ...
    baseline.requirementsMet && strcmp(baseline.failureMode,'none'), ...
    'Baseline must remain in both tolerance bands by the 1200 ms deadline.');

smallCommand = model(10,1.5,0.7,45,0.5,2,1200);
largeCommand = model(40,1.5,0.7,45,0.5,2,1200);
assert(abs(largeCommand.peakPositionMagnitudeDeg/ ...
    smallCommand.peakPositionMagnitudeDeg - 4) < 1e-12, ...
    'Position response must scale linearly with command magnitude.');
assert(abs(largeCommand.peakVelocityMagnitudeDegPerSec/ ...
    smallCommand.peakVelocityMagnitudeDegPerSec - 4) < 1e-12, ...
    'Velocity response must scale linearly with command magnitude.');
assert(abs(largeCommand.overshootPercent - smallCommand.overshootPercent) < 1e-12, ...
    'Command magnitude must not change normalized overshoot.');

lowDamping = model(30,1.5,0.25,45,0.5,2,1200);
criticalDamping = model(30,1.5,1,45,0.5,2,1200);
assert(lowDamping.overshootPercent > 44 && ...
    criticalDamping.overshootPercent < 1e-9, ...
    'Damping limits must distinguish oscillatory and non-overshooting motion.');
assert(~lowDamping.settledByDeadline && ...
    strcmp(lowDamping.failureMode,'deadline-missed'), ...
    'Low damping must expose the response-deadline failure.');
assert(criticalDamping.settledByDeadline && criticalDamping.requirementsMet, ...
    'The critical-damping limiting case must meet this behavior envelope.');

zeroCommand = model(0,1.5,0.7,45,0.5,2,1200);
assert(all(zeroCommand.positionDeg == 0) && all(zeroCommand.velocityDegPerSec == 0), ...
    'A zero command from zero initial state must produce no physical motion.');
assert(zeroCommand.overshootPercent == 0 && zeroCommand.settlingTimeMs == 0 && ...
    zeroCommand.requirementsMet, ...
    'Zero-command overshoot and settling semantics changed unexpectedly.');
slowCriticalZero = model(0,0.001,1,45,0.5,2,1200);
assert(slowCriticalZero.settlingTimeMs == 0 && ...
    slowCriticalZero.requestFutureGuaranteed && slowCriticalZero.requirementsMet, ...
    'Zero input must remain settled even when a theoretical response rate is very slow.');

negativeCommand = model(-30,1.5,0.7,45,0.5,2,1200);
assert(max(abs(negativeCommand.positionDeg + baseline.positionDeg)) < 1e-12 && ...
    max(abs(negativeCommand.velocityDegPerSec + baseline.velocityDegPerSec)) < 1e-12, ...
    'A negative command must be the signed mirror of the positive response.');
assert(negativeCommand.directionCorrect && negativeCommand.requirementsMet && ...
    negativeCommand.settlingTimeMs == baseline.settlingTimeMs, ...
    'Signed behavior must preserve timing and magnitude requirements.');

exactAuthority = model(45,1.5,0.7,45,0.5,2,1200);
assert(~exactAuthority.commandWasLimited && exactAuthority.effectiveCommandDeg == 45, ...
    'A command exactly at the declared authority boundary must be accepted.');
deadlineMiss = model(30,1.5,0.7,45,0.5,2,500);
assert(deadlineMiss.settlingTimeMs == baseline.settlingTimeMs && ...
    ~deadlineMiss.settledByDeadline && ~deadlineMiss.requirementsMet && ...
    strcmp(deadlineMiss.failureMode,'deadline-missed'), ...
    'A short deadline must report late behavior without changing the trajectory.');
deadlineTie = model(30,1.5,0.7,45,0.5,2,780);
oneSampleEarly = model(30,1.5,0.7,45,0.5,2,778);
assert(deadlineTie.settledByDeadline && deadlineTie.requirementsMet && ...
    ~oneSampleEarly.settledByDeadline && ~oneSampleEarly.requirementsMet, ...
    'Settling exactly at the deadline must pass; one sample earlier must fail.');
fractionalDeadline = model(30,1.5,0.7,45,0.5,2,781);
assert(fractionalDeadline.deadlineSampleTimeMs == 780, ...
    'Deadline observables must expose the latest modeled sample at or before the deadline.');

nearCritical = model(30,1.5,1-eps,45,0.5,2,1200);
assert(all(~isinf(nearCritical.positionDeg) & ~isnan(nearCritical.positionDeg)) && ...
    all(~isinf(nearCritical.velocityDegPerSec) & ~isnan(nearCritical.velocityDegPerSec)) && ...
    abs(nearCritical.overshootPercent - criticalDamping.overshootPercent) < 1e-8 && ...
    abs(nearCritical.settlingTimeMs - criticalDamping.settlingTimeMs) <= 2, ...
    'The underdamped formula must remain finite and continuous near critical damping.');
finiteHorizonTrap = model(30,10,0.022,45,0.5,2,3000);
assert(~finiteHorizonTrap.settledByDeadline && ...
    finiteHorizonTrap.settlingTimeMs > finiteHorizonTrap.inputs.deadlineMs, ...
    'A final-sample band entry must not masquerade as sustained settling.');

brokenAuthority = model(70,1.5,0.7,45,0.5,2,1200);
assert(brokenAuthority.commandWasLimited && ...
    brokenAuthority.effectiveCommandDeg == 45 && ...
    brokenAuthority.commandAuthorityMarginDeg == -25, ...
    'The broken input-envelope case must expose the requested and applied commands.');
assert(brokenAuthority.effectiveTargetSettledByDeadline && ...
    ~brokenAuthority.settledByDeadline && isinf(brokenAuthority.settlingTimeMs), ...
    'The plant may settle to the limited target without achieving the request.');
assert(~brokenAuthority.requirementsMet && ...
    strcmp(brokenAuthority.failureMode,'command-limited') && ...
    brokenAuthority.finalRequestErrorDeg > 24.9, ...
    'Command limiting must remain a recognizable steady-state failure.');

compatible = model(int16(30),single(1.5),single(0.5),uint16(45), ...
    single(0.5),uint16(2),uint16(1200));
compatibleReference = model(30,1.5,0.5,45,0.5,2,1200);
assert(isequaln(compatible,compatibleReference), ...
    'Compatible numeric scalar classes must normalize to the same response.');

expectAnyError(@() model(NaN,1.5,0.7,45,0.5,2,1200));
expectAnyError(@() model(Inf,1.5,0.7,45,0.5,2,1200));
expectAnyError(@() model(1+1i,1.5,0.7,45,0.5,2,1200));
expectAnyError(@() model([20 30],1.5,0.7,45,0.5,2,1200));
expectAnyError(@() model(30,0,0.7,45,0.5,2,1200));
expectAnyError(@() model(30,1.5,0.7,-1,0.5,2,1200));
expectAnyError(@() model(30,1.5,0.7,45,0,2,1200));
expectAnyError(@() model(30,1.5,0.7,45,0.5,0,1200));
expectAnyError(@() model(30,1.5,0.7,45,0.5,2,0));
expectErrorId(@() model(30,1.5,0,45,0.5,2,1200), ...
    'P03:InvalidDampingRatio');
expectErrorId(@() model(30,1.5,1.1,45,0.5,2,1200), ...
    'P03:InvalidDampingRatio');
expectErrorId(@() model(30,1.5,0.7,0.25,0.5,2,1200), ...
    'P03:InvalidTolerance');
expectErrorId(@() model(181,1.5,0.7,45,0.5,2,1200), ...
    'P03:ResourceBound');
expectErrorId(@() model(30,10.1,0.7,45,0.5,2,1200), ...
    'P03:ResourceBound');
expectErrorId(@() model(30,1.5,0.7,181,0.5,2,1200), ...
    'P03:ResourceBound');
expectErrorId(@() model(30,1.5,0.7,45,31,2,1200), ...
    'P03:ResourceBound');
expectErrorId(@() model(30,1.5,0.7,45,0.5,1001,1200), ...
    'P03:ResourceBound');
expectErrorId(@() model(30,1.5,0.7,45,0.5,2,3001), ...
    'P03:ResourceBound');

afterFailure = model(30,1.5,0.7,45,0.5,2,1200);
assert(isequaln(afterFailure,baseline), ...
    'A valid call after malformed and broken cases must recover without hidden state.');
afterIsolationProbe = model(30,1.5,0.7,45,0.5,2,1200);
assert(isequaln(afterIsolationProbe,baseline), ...
    'Independent model calls must remain isolated from prior commands.');
disp('P03 checks passed: baseline, limits, levers, failures, recovery, and bounds.');
end

function expectAnyError(callable)
didThrow = false;
try
    callable();
catch
    didThrow = true;
end
assert(didThrow,'Malformed input must be rejected.');
end

function expectErrorId(callable,expectedId)
didThrow = false;
try
    callable();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedId), ...
        sprintf('Unexpected error identifier: %s',exception.identifier));
end
assert(didThrow,sprintf('Expected error %s was not raised.',expectedId));
end
